import { shiftDay, todayKey } from './format';
import type { Entity } from './store';
import type {
  Badge,
  Booking,
  Delivery,
  GatherEvent,
  Meeting,
  Notification,
  Order,
  Space,
  Task,
  Ticket,
  Visit,
} from './data';

type New<T> = Omit<T, keyof Entity>;

type Hold = Omit<New<Booking>, 'space' | 'level' | 'capacity'>;

type EventSeed = Omit<New<GatherEvent>, 'location'> & { location?: string };

const day = (offset: number): string => shiftDay(todayKey(), offset);

const at = (clock: string, offset = 0): string => {
  const [hours, minutes] = clock.split(':').map(Number);
  const date = new Date(`${day(offset)}T00:00:00`);
  date.setHours(hours, minutes, 0, 0);
  return date.toISOString();
};

const minutesFromNow = (offset: number): string => {
  const date = new Date();
  date.setMinutes(date.getMinutes() + offset, 0, 0);
  return date.toISOString();
};

export const PEOPLE = [
  { name: 'Sara Ahmed', role: 'Product Design Lead', team: 'Design' },
  { name: 'Karim Fouad', role: 'Engineering Manager', team: 'Engineering' },
  { name: 'Nadia Salem', role: 'Staff Engineer', team: 'Engineering' },
  { name: 'Hana Youssef', role: 'Partnerships Lead', team: 'Commercial' },
  { name: 'Omar Zaki', role: 'Data Scientist', team: 'Data' },
  { name: 'Lina Haddad', role: 'People Partner', team: 'People' },
  { name: 'Yousef Mansour', role: 'Facilities Manager', team: 'Workplace' },
  { name: 'Rana Khalil', role: 'Brand Designer', team: 'Design' },
  { name: 'Tarek Aziz', role: 'Finance Analyst', team: 'Finance' },
  { name: 'Mona Darwish', role: 'Wellness Coach', team: 'People' },
  { name: 'Adel Rashid', role: 'Security Lead', team: 'Workplace' },
  { name: 'Farah Nabil', role: 'Content Strategist', team: 'Marketing' },
  { name: 'Bassem Riad', role: 'IT Support Engineer', team: 'IT' },
  { name: 'Dina Hafez', role: 'Technical Recruiter', team: 'People' },
  { name: 'Ziad Morsi', role: 'Solutions Architect', team: 'Engineering' },
  { name: 'Salma Gaber', role: 'Community Manager', team: 'Marketing' },
  { name: 'Noura Sami', role: 'Chief of Staff', team: 'Executive' },
  { name: 'Hassan Iqbal', role: 'Café Manager', team: 'Workplace' },
  { name: 'Maya Fahmy', role: 'Product Manager', team: 'Product' },
  { name: 'Tamer Sobhy', role: 'QA Lead', team: 'Engineering' },
  { name: 'Reem Othman', role: 'UX Researcher', team: 'Design' },
  { name: 'Fadi Barakat', role: 'Account Executive', team: 'Commercial' },
  { name: 'Laila Mostafa', role: 'Legal Counsel', team: 'Legal' },
  { name: 'Sami Kamal', role: 'DevOps Engineer', team: 'Engineering' },
  { name: 'Amira Shafik', role: 'Marketing Manager', team: 'Marketing' },
  { name: 'Khaled Nour', role: 'Sales Director', team: 'Commercial' },
  { name: 'Yara Sabry', role: 'Front-end Engineer', team: 'Engineering' },
  { name: 'Waleed Tantawy', role: 'Procurement Lead', team: 'Finance' },
];

export const SPACES: Array<New<Space> & { id: string }> = [
  { id: 'atrium', name: 'The Atrium', kind: 'Training', level: 'Level 1', capacity: 30, amenities: ['Display', 'Catering', 'Daylight'], utilisation: 88, offline: false, approval: true },
  { id: 'forum', name: 'The Forum', kind: 'Training', level: 'Level 1', capacity: 120, amenities: ['Stage', 'Video', 'Display', 'Catering'], utilisation: 61, offline: false, approval: true },
  { id: 'studio-3', name: 'Studio 3', kind: 'Meeting room', level: 'Level 2', capacity: 8, amenities: ['Video', 'Whiteboard', 'Display'], utilisation: 64, offline: false, approval: false },
  { id: 'studio-4', name: 'Studio 4', kind: 'Meeting room', level: 'Level 2', capacity: 6, amenities: ['Video', 'Whiteboard'], utilisation: 47, offline: false, approval: false },
  { id: 'pod-2a', name: 'Pod 2-A', kind: 'Focus pod', level: 'Level 2', capacity: 1, amenities: ['Soundproof'], utilisation: 71, offline: false, approval: false },
  { id: 'pod-2b', name: 'Pod 2-B', kind: 'Focus pod', level: 'Level 2', capacity: 1, amenities: ['Soundproof'], utilisation: 34, offline: false, approval: false },
  { id: 'cedar', name: 'Cedar', kind: 'Meeting room', level: 'Level 3', capacity: 6, amenities: ['Display', 'Whiteboard'], utilisation: 52, offline: false, approval: false },
  { id: 'jasmine', name: 'Jasmine', kind: 'Huddle', level: 'Level 3', capacity: 4, amenities: ['Display'], utilisation: 41, offline: false, approval: false },
  { id: 'olive', name: 'Olive', kind: 'Huddle', level: 'Level 3', capacity: 4, amenities: ['Whiteboard'], utilisation: 29, offline: false, approval: false },
  { id: 'lab', name: 'Innovation Lab', kind: 'Training', level: 'Level 3', capacity: 24, amenities: ['Whiteboard', 'Display', 'Daylight'], utilisation: 57, offline: false, approval: false },
  { id: 'maple', name: 'Maple', kind: 'Meeting room', level: 'Level 4', capacity: 8, amenities: ['Video', 'Display'], utilisation: 66, offline: false, approval: false },
  { id: 'desk-4-118', name: 'Desk 4-118', kind: 'Desk', level: 'Level 4', capacity: 1, amenities: ['Dual monitors', 'Daylight'], utilisation: 30, offline: false, approval: false },
  { id: 'desk-4-120', name: 'Desk 4-120', kind: 'Desk', level: 'Level 4', capacity: 1, amenities: ['Standing desk'], utilisation: 12, offline: true, approval: false, note: 'Monitor arm replacement — back Thursday.' },
  { id: 'desk-4-122', name: 'Desk 4-122', kind: 'Desk', level: 'Level 4', capacity: 1, amenities: ['Dual monitors'], utilisation: 44, offline: false, approval: false },
  { id: 'orchid', name: 'Orchid', kind: 'Meeting room', level: 'Level 5', capacity: 12, amenities: ['Video', 'Display', 'Catering'], utilisation: 78, offline: false, approval: true },
  { id: 'lotus', name: 'Lotus', kind: 'Meeting room', level: 'Level 5', capacity: 10, amenities: ['Video', 'Whiteboard', 'Daylight'], utilisation: 55, offline: false, approval: false },
  { id: 'boardroom', name: 'The Boardroom', kind: 'Meeting room', level: 'Level 6', capacity: 14, amenities: ['Video', 'Catering', 'Daylight'], utilisation: 23, offline: false, approval: true },
  { id: 'skyline', name: 'Skyline Lounge', kind: 'Training', level: 'Level 6', capacity: 40, amenities: ['Display', 'Catering', 'Daylight'], utilisation: 49, offline: false, approval: true },
  { id: 'roof-garden', name: 'Roof Garden', kind: 'Training', level: 'Level 7', capacity: 60, amenities: ['Daylight', 'Catering'], utilisation: 36, offline: false, approval: true },
];

const spaceById = new Map(SPACES.map((space) => [space.id, space]));

const where = (spaceId: string): string => {
  const space = spaceById.get(spaceId);
  return space ? `${space.name} · ${space.level}` : 'Riyadh HQ';
};

const EVENT_SEED: Array<EventSeed & { id: string }> = [
  {
    id: 'ev-townhall-q3',
    title: 'Q3 All-Hands',
    category: 'Town hall',
    mode: 'Hybrid',
    date: day(-7),
    start: '14:00',
    end: '15:30',
    spaceId: 'forum',
    host: 'Noura Sami',
    team: 'Executive',
    capacity: 120,
    price: 0,
    required: true,
    status: 'published',
    summary: 'Quarterly numbers, the roadmap reset, and the people awards. Streamed for anyone off site.',
    tags: ['Company', 'Strategy'],
    going: ['Sara Ahmed', 'Karim Fouad', 'Nadia Salem', 'Hana Youssef', 'Omar Zaki', 'Lina Haddad', 'Yousef Mansour', 'Rana Khalil', 'Tarek Aziz', 'Adel Rashid', 'Farah Nabil', 'Ziad Morsi', 'Noura Sami', 'Maya Fahmy', 'Reem Othman', 'Laila Mostafa', 'Amira Shafik', 'Khaled Nour'],
    waitlist: [],
  },
  {
    id: 'ev-hack-day',
    title: 'Internal Hack Day',
    category: 'Learning',
    mode: 'In person',
    date: day(-4),
    start: '09:00',
    end: '17:00',
    spaceId: 'lab',
    host: 'Karim Fouad',
    team: 'Engineering',
    capacity: 24,
    price: 0,
    required: false,
    status: 'published',
    summary: 'One day, one prototype. Teams of three, demos at four, the winner ships next sprint.',
    tags: ['Engineering', 'Prototyping'],
    going: ['Karim Fouad', 'Nadia Salem', 'Ziad Morsi', 'Sami Kamal', 'Yara Sabry', 'Tamer Sobhy', 'Omar Zaki', 'Maya Fahmy', 'Sara Ahmed', 'Bassem Riad'],
    waitlist: [],
  },
  {
    id: 'ev-coffee-tasting',
    title: 'Single-Origin Coffee Tasting',
    category: 'Social',
    mode: 'In person',
    date: day(-1),
    start: '15:00',
    end: '16:00',
    spaceId: 'atrium',
    host: 'Hassan Iqbal',
    team: 'Workplace',
    capacity: 24,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Four roasts from three farms, poured side by side. Bring a cup and an opinion.',
    tags: ['Coffee', 'Tasting'],
    going: ['Hassan Iqbal', 'Sara Ahmed', 'Rana Khalil', 'Farah Nabil', 'Salma Gaber', 'Reem Othman', 'Dina Hafez', 'Amira Shafik', 'Tarek Aziz'],
    waitlist: [],
  },
  {
    id: 'ev-yoga',
    title: 'Sunrise Yoga Flow',
    category: 'Wellness',
    mode: 'In person',
    date: day(0),
    start: '08:00',
    end: '09:00',
    spaceId: 'roof-garden',
    host: 'Mona Darwish',
    team: 'People',
    capacity: 24,
    price: 0,
    required: false,
    status: 'published',
    summary: 'A slow start on the roof before the inbox opens. Mats and towels are laid out for you.',
    tags: ['Wellness', 'Movement'],
    going: ['Mona Darwish', 'Sara Ahmed', 'Lina Haddad', 'Reem Othman', 'Rana Khalil', 'Dina Hafez', 'Yara Sabry', 'Amira Shafik', 'Maya Fahmy', 'Salma Gaber', 'Laila Mostafa'],
    waitlist: [],
  },
  {
    id: 'ev-lunch-learn',
    title: 'Lunch & Learn: Design Systems at Scale',
    category: 'Learning',
    mode: 'Hybrid',
    date: day(0),
    start: '12:30',
    end: '13:30',
    spaceId: 'lab',
    host: 'Sara Ahmed',
    team: 'Design',
    capacity: 24,
    price: 0,
    required: false,
    status: 'published',
    summary: 'How the token layer cut our design-to-ship time in half, and the three places it still hurts.',
    tags: ['Design', 'Tokens', 'Lunch provided'],
    going: ['Sara Ahmed', 'Rana Khalil', 'Reem Othman', 'Yara Sabry', 'Maya Fahmy', 'Nadia Salem', 'Farah Nabil', 'Ziad Morsi', 'Tamer Sobhy', 'Karim Fouad', 'Salma Gaber', 'Bassem Riad', 'Omar Zaki', 'Dina Hafez'],
    waitlist: ['Fadi Barakat', 'Waleed Tantawy'],
  },
  {
    id: 'ev-new-joiner',
    title: 'New Joiner Welcome',
    category: 'Culture',
    mode: 'In person',
    date: day(0),
    start: '16:00',
    end: '17:30',
    spaceId: 'skyline',
    host: 'Lina Haddad',
    team: 'People',
    capacity: 40,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Nine people joined this month. Come put faces to the names over something cold.',
    tags: ['Culture', 'Onboarding'],
    going: ['Lina Haddad', 'Dina Hafez', 'Noura Sami', 'Sara Ahmed', 'Karim Fouad', 'Hana Youssef', 'Salma Gaber', 'Yousef Mansour', 'Maya Fahmy', 'Amira Shafik', 'Fadi Barakat', 'Khaled Nour'],
    waitlist: [],
  },
  {
    id: 'ev-townhall-q4',
    title: 'Q4 All-Hands',
    category: 'Town hall',
    mode: 'Hybrid',
    date: day(1),
    start: '14:00',
    end: '15:30',
    spaceId: 'forum',
    host: 'Noura Sami',
    team: 'Executive',
    capacity: 120,
    price: 0,
    required: true,
    status: 'published',
    summary: 'Where we landed the quarter, what changes in January, and twenty minutes of open questions.',
    tags: ['Company', 'Strategy'],
    going: ['Noura Sami', 'Sara Ahmed', 'Karim Fouad', 'Hana Youssef', 'Nadia Salem', 'Omar Zaki', 'Lina Haddad', 'Tarek Aziz', 'Rana Khalil', 'Adel Rashid', 'Maya Fahmy', 'Ziad Morsi', 'Laila Mostafa', 'Khaled Nour', 'Amira Shafik', 'Waleed Tantawy'],
    waitlist: [],
  },
  {
    id: 'ev-run-club',
    title: 'Riyadh Run Club',
    category: 'Wellness',
    mode: 'In person',
    date: day(1),
    start: '18:00',
    end: '19:30',
    location: 'Wadi Hanifah trail · meet at reception',
    host: 'Tamer Sobhy',
    team: 'Engineering',
    capacity: 20,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Five kilometres along the wadi at an easy pace. Nobody gets left behind, nobody gets timed.',
    tags: ['Running', 'Outdoors'],
    going: ['Tamer Sobhy', 'Sami Kamal', 'Yara Sabry', 'Mona Darwish', 'Omar Zaki', 'Fadi Barakat', 'Karim Fouad'],
    waitlist: [],
  },
  {
    id: 'ev-latte-art',
    title: 'Barista Workshop: Latte Art',
    category: 'Social',
    mode: 'In person',
    date: day(2),
    start: '16:00',
    end: '17:30',
    spaceId: 'atrium',
    host: 'Hassan Iqbal',
    team: 'Workplace',
    capacity: 12,
    price: 75,
    required: false,
    status: 'published',
    summary: 'Pour a rosetta that holds its shape. Beans to take home, and the milk is on us.',
    tags: ['Coffee', 'Workshop'],
    going: ['Hassan Iqbal', 'Rana Khalil', 'Reem Othman', 'Salma Gaber', 'Farah Nabil', 'Dina Hafez', 'Amira Shafik', 'Maya Fahmy', 'Yara Sabry', 'Lina Haddad', 'Sara Ahmed', 'Mona Darwish'],
    waitlist: ['Tarek Aziz', 'Bassem Riad', 'Nadia Salem'],
  },
  {
    id: 'ev-ai-guild',
    title: 'AI Guild: Agents in Production',
    category: 'Learning',
    mode: 'Hybrid',
    date: day(3),
    start: '11:00',
    end: '12:30',
    spaceId: 'forum',
    host: 'Ziad Morsi',
    team: 'Engineering',
    capacity: 60,
    price: 0,
    required: false,
    status: 'published',
    summary: 'What broke when we put agents in front of real customers, and the guardrails that held.',
    tags: ['AI', 'Architecture'],
    going: ['Ziad Morsi', 'Nadia Salem', 'Omar Zaki', 'Sami Kamal', 'Karim Fouad', 'Tamer Sobhy', 'Yara Sabry', 'Maya Fahmy', 'Sara Ahmed', 'Bassem Riad', 'Reem Othman'],
    waitlist: [],
  },
  {
    id: 'ev-board-games',
    title: 'Board Game Night',
    category: 'Social',
    mode: 'In person',
    date: day(3),
    start: '17:30',
    end: '20:00',
    spaceId: 'skyline',
    host: 'Salma Gaber',
    team: 'Marketing',
    capacity: 30,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Catan, Codenames and a worryingly competitive Uno table. Pizza lands at six.',
    tags: ['Games', 'Food'],
    going: ['Salma Gaber', 'Farah Nabil', 'Bassem Riad', 'Tamer Sobhy', 'Yara Sabry', 'Sami Kamal', 'Dina Hafez', 'Fadi Barakat'],
    waitlist: [],
  },
  {
    id: 'ev-first-aid',
    title: 'First Aid Certification',
    category: 'Wellness',
    mode: 'In person',
    date: day(4),
    start: '09:00',
    end: '13:00',
    spaceId: 'lab',
    host: 'Adel Rashid',
    team: 'Workplace',
    capacity: 16,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Certified by the Red Crescent, valid three years. Half a day, and you leave able to help.',
    tags: ['Safety', 'Certification'],
    going: ['Adel Rashid', 'Yousef Mansour', 'Mona Darwish', 'Hassan Iqbal', 'Lina Haddad', 'Bassem Riad', 'Waleed Tantawy', 'Tarek Aziz', 'Khaled Nour', 'Laila Mostafa', 'Amira Shafik', 'Omar Zaki', 'Sami Kamal', 'Dina Hafez', 'Fadi Barakat', 'Noura Sami'],
    waitlist: ['Sara Ahmed', 'Rana Khalil', 'Maya Fahmy'],
  },
  {
    id: 'ev-vendor-fair',
    title: 'Workplace Vendor Fair',
    category: 'Culture',
    mode: 'In person',
    date: day(5),
    start: '11:00',
    end: '15:00',
    spaceId: 'atrium',
    host: 'Waleed Tantawy',
    team: 'Finance',
    capacity: 30,
    price: 0,
    required: false,
    status: 'cancelled',
    summary: 'Pulled back to January — three of the six suppliers could not make the new date.',
    tags: ['Procurement'],
    going: ['Waleed Tantawy', 'Yousef Mansour', 'Tarek Aziz'],
    waitlist: [],
  },
  {
    id: 'ev-design-crit',
    title: 'Open Design Critique',
    category: 'Learning',
    mode: 'In person',
    date: day(7),
    start: '10:00',
    end: '11:30',
    spaceId: 'studio-3',
    host: 'Reem Othman',
    team: 'Design',
    capacity: 8,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Bring one screen you are unsure about. Kind, specific, and no deck required.',
    tags: ['Design', 'Feedback'],
    going: ['Reem Othman', 'Sara Ahmed', 'Rana Khalil', 'Maya Fahmy', 'Yara Sabry', 'Farah Nabil', 'Salma Gaber', 'Amira Shafik'],
    waitlist: ['Nadia Salem', 'Dina Hafez'],
  },
  {
    id: 'ev-culture-day',
    title: 'Culture Day Potluck',
    category: 'Culture',
    mode: 'In person',
    date: day(9),
    start: '12:00',
    end: '14:30',
    spaceId: 'atrium',
    host: 'Salma Gaber',
    team: 'Marketing',
    capacity: 30,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Twenty-two nationalities, one very long table. Bring a dish that means something to you.',
    tags: ['Culture', 'Food'],
    going: ['Salma Gaber', 'Lina Haddad', 'Hassan Iqbal', 'Farah Nabil', 'Dina Hafez', 'Amira Shafik', 'Khaled Nour', 'Laila Mostafa', 'Reem Othman', 'Rana Khalil', 'Waleed Tantawy', 'Fadi Barakat', 'Mona Darwish'],
    waitlist: [],
  },
  {
    id: 'ev-security-brief',
    title: 'Security Awareness Briefing',
    category: 'Learning',
    mode: 'Virtual',
    date: day(10),
    start: '10:00',
    end: '11:00',
    location: 'Streamed — joining link in the invite',
    host: 'Adel Rashid',
    team: 'Workplace',
    capacity: 120,
    price: 0,
    required: true,
    status: 'published',
    summary: 'The annual one. Phishing, tailgating, and what to do in the ninety seconds after a mistake.',
    tags: ['Security', 'Mandatory'],
    going: ['Adel Rashid', 'Bassem Riad', 'Laila Mostafa', 'Noura Sami', 'Karim Fouad', 'Sami Kamal', 'Tarek Aziz', 'Waleed Tantawy', 'Ziad Morsi'],
    waitlist: [],
  },
  {
    id: 'ev-summit',
    title: 'Dixels Tech Summit 2026',
    category: 'Learning',
    mode: 'Hybrid',
    date: day(14),
    start: '09:00',
    end: '17:00',
    spaceId: 'forum',
    host: 'Karim Fouad',
    team: 'Engineering',
    capacity: 120,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Our flagship day: two keynotes, eight breakouts on platform, data and design, and a long lunch.',
    tags: ['Flagship', 'Keynote', 'Networking'],
    going: ['Karim Fouad', 'Nadia Salem', 'Ziad Morsi', 'Sami Kamal', 'Yara Sabry', 'Tamer Sobhy', 'Omar Zaki', 'Sara Ahmed', 'Rana Khalil', 'Reem Othman', 'Maya Fahmy', 'Bassem Riad', 'Noura Sami', 'Hana Youssef', 'Farah Nabil', 'Salma Gaber', 'Amira Shafik', 'Khaled Nour', 'Fadi Barakat', 'Dina Hafez', 'Lina Haddad', 'Mona Darwish'],
    waitlist: [],
  },
  {
    id: 'ev-wellness-week',
    title: 'Wellness Week Kickoff',
    category: 'Wellness',
    mode: 'In person',
    date: day(16),
    start: '08:30',
    end: '10:00',
    spaceId: 'roof-garden',
    host: 'Mona Darwish',
    team: 'People',
    capacity: 60,
    price: 0,
    required: false,
    status: 'draft',
    summary: 'Still pinning down the physio and the smoothie cart before this one goes out to everyone.',
    tags: ['Wellness'],
    going: ['Mona Darwish'],
    waitlist: [],
  },
];

export const EVENTS = EVENT_SEED.map((event) => ({
  ...event,
  location: event.location ?? where(event.spaceId ?? ''),
}));

export const VISITS: New<Visit>[] = [
  { guest: 'Layla Nasser', company: 'Northwind', host: 'Sara Ahmed', date: day(0), time: '13:00', purpose: 'Quarterly review', status: 'pre-registered', email: 'layla.nasser@northwind.com', kind: 'VIP', spaceId: 'orchid', location: where('orchid'), parking: true, code: 'VF-4180' },
  { guest: 'Omar Haddad', company: 'Vertex Labs', host: 'Sara Ahmed', date: day(0), time: '15:30', purpose: 'Partnership intro', status: 'invited', email: 'o.haddad@vertexlabs.io', kind: 'Guest', spaceId: 'studio-3', location: where('studio-3'), parking: false, code: 'VF-7723' },
  { guest: 'Mei Chen', company: 'Aurora', host: 'Karim Fouad', date: day(0), time: '09:15', purpose: 'Onsite audit', status: 'checked-in', email: 'mei.chen@aurora.co', kind: 'Vendor', location: 'Level 4 lounge', parking: false, code: 'VF-2094', badge: '104', arrivedAt: minutesFromNow(-95) },
  { guest: 'Rami Barakat', company: 'Cobalt Systems', host: 'Nadia Salem', date: day(0), time: '10:30', purpose: 'Integration workshop', status: 'checked-in', email: 'r.barakat@cobaltsys.com', kind: 'Vendor', spaceId: 'cedar', location: where('cedar'), parking: true, code: 'VF-8812', badge: '102', arrivedAt: minutesFromNow(-240) },
  { guest: 'Ingrid Sørensen', company: 'Nordic Retail', host: 'Hana Youssef', date: day(0), time: '11:00', purpose: 'Contract walkthrough', status: 'checked-in', email: 'ingrid@nordicretail.no', kind: 'VIP', spaceId: 'lotus', location: where('lotus'), parking: true, code: 'VF-6630', badge: 'VIP-01', arrivedAt: minutesFromNow(-180) },
  { guest: 'Tom Whitfield', company: 'Greenline Facilities', host: 'Yousef Mansour', date: day(0), time: '08:30', purpose: 'HVAC inspection', status: 'checked-out', email: 't.whitfield@greenline.co.uk', kind: 'Contractor', location: 'Level 6 plant room', parking: true, code: 'VF-1187', badge: '103', arrivedAt: minutesFromNow(-560), leftAt: minutesFromNow(-320) },
  { guest: 'Yasmine Toure', company: 'Atlas Capital', host: 'Tarek Aziz', date: day(0), time: '16:30', purpose: 'Funding checkpoint', status: 'pre-registered', email: 'y.toure@atlascapital.com', kind: 'VIP', spaceId: 'boardroom', location: where('boardroom'), parking: true, code: 'VF-9041' },
  { guest: 'Daniel Okafor', company: 'Helios Group', host: 'Sara Ahmed', date: day(1), time: '11:00', purpose: 'Design portfolio review', status: 'invited', email: 'd.okafor@helios.group', kind: 'Interview', spaceId: 'studio-3', location: where('studio-3'), parking: false, code: 'VF-5516' },
  { guest: 'Claire Dubois', company: 'Lumen Studio', host: 'Rana Khalil', date: day(1), time: '14:00', purpose: 'Brand refresh pitch', status: 'pre-registered', email: 'claire@lumen.studio', kind: 'Guest', spaceId: 'studio-4', location: where('studio-4'), parking: false, code: 'VF-7208' },
  { guest: 'Abdullah Al-Harbi', company: 'Ministry of Investment', host: 'Noura Sami', date: day(1), time: '10:00', purpose: 'Delegation tour', status: 'pre-registered', email: 'a.alharbi@mise.gov.sa', kind: 'VIP', spaceId: 'boardroom', location: where('boardroom'), parking: true, code: 'VF-3355' },
  { guest: 'Priya Raman', company: 'Meridian', host: 'Sara Ahmed', date: day(-1), time: '14:00', purpose: 'Contract signing', status: 'checked-out', email: 'praman@meridian.com', kind: 'Guest', spaceId: 'orchid', location: where('orchid'), parking: true, code: 'VF-3341', arrivedAt: at('14:02', -1), leftAt: at('15:20', -1) },
  { guest: 'Marcus Reed', company: 'Vertex Labs', host: 'Hana Youssef', date: day(-1), time: '09:30', purpose: 'Technical deep dive', status: 'checked-out', email: 'm.reed@vertexlabs.io', kind: 'Guest', spaceId: 'maple', location: where('maple'), parking: false, code: 'VF-2276', arrivedAt: at('09:35', -1), leftAt: at('12:10', -1) },
  { guest: 'Sofia Marchetti', company: 'Alpine Foods', host: 'Hassan Iqbal', date: day(-1), time: '11:00', purpose: 'Catering tasting', status: 'checked-out', email: 'sofia@alpinefoods.it', kind: 'Vendor', location: 'Smart Café · Level 1', parking: false, code: 'VF-4409', arrivedAt: at('11:05', -1), leftAt: at('13:00', -1) },
  { guest: 'Jonas Weber', company: 'Helios Group', host: 'Dina Hafez', date: day(2), time: '09:30', purpose: 'Engineering interview', status: 'invited', email: 'j.weber@helios.group', kind: 'Interview', spaceId: 'olive', location: where('olive'), parking: false, code: 'VF-6127' },
  { guest: 'Nour Al-Din', company: 'Cobalt Systems', host: 'Sara Ahmed', date: day(2), time: '15:00', purpose: 'Design system audit', status: 'invited', email: 'n.aldin@cobaltsys.com', kind: 'Vendor', spaceId: 'studio-4', location: where('studio-4'), parking: false, code: 'VF-9318' },
  { guest: 'Grace Mwangi', company: 'Lumen Studio', host: 'Sara Ahmed', date: day(3), time: '11:30', purpose: 'Senior designer interview', status: 'invited', email: 'grace@lumen.studio', kind: 'Interview', spaceId: 'jasmine', location: where('jasmine'), parking: false, code: 'VF-4472' },
  { guest: 'Idris Lawal', company: 'Northwind', host: 'Sara Ahmed', date: day(-1), time: '16:00', purpose: 'Design handover', status: 'checked-out', email: 'i.lawal@northwind.com', kind: 'Guest', spaceId: 'studio-3', location: where('studio-3'), parking: false, code: 'VF-2650', arrivedAt: at('16:03', -1), leftAt: at('17:15', -1) },
  { guest: 'Aisha Bello', company: 'Northwind', host: 'Hana Youssef', date: day(2), time: '13:30', purpose: 'Renewal negotiation', status: 'invited', email: 'a.bello@northwind.com', kind: 'VIP', spaceId: 'orchid', location: where('orchid'), parking: true, code: 'VF-8874' },
  { guest: 'Victor Santos', company: 'Cobalt Systems', host: 'Ziad Morsi', date: day(3), time: '10:00', purpose: 'Architecture review', status: 'invited', email: 'v.santos@cobaltsys.com', kind: 'Vendor', spaceId: 'maple', location: where('maple'), parking: false, code: 'VF-5590' },
  { guest: 'Hala Mansour', company: 'Meridian', host: 'Laila Mostafa', date: day(3), time: '15:00', purpose: 'Compliance audit', status: 'invited', email: 'h.mansour@meridian.com', kind: 'Guest', spaceId: 'lotus', location: where('lotus'), parking: false, code: 'VF-1902' },
  { guest: 'Erik Lindqvist', company: 'Nordic Retail', host: 'Khaled Nour', date: day(4), time: '11:30', purpose: 'Expansion planning', status: 'invited', email: 'erik@nordicretail.no', kind: 'VIP', spaceId: 'boardroom', location: where('boardroom'), parking: true, code: 'VF-7745' },
];

const DESK_AND_ROOM_HOLDS: Hold[] = [
  { spaceId: 'studio-3', date: day(0), start: '10:00', end: '11:00', purpose: 'Design sync', status: 'checked-in', organizer: 'Sara Ahmed', attendees: 3, checkedInAt: at('09:58') },
  { spaceId: 'cedar', date: day(0), start: '09:00', end: '10:30', purpose: 'Sprint planning', status: 'confirmed', organizer: 'Karim Fouad', attendees: 5 },
  { spaceId: 'jasmine', date: day(0), start: '11:00', end: '12:00', purpose: 'Pair review', status: 'confirmed', organizer: 'Nadia Salem', attendees: 2 },
  { spaceId: 'jasmine', date: day(0), start: '14:30', end: '15:30', purpose: 'Roadmap triage', status: 'confirmed', organizer: 'Maya Fahmy', attendees: 4 },
  { spaceId: 'olive', date: day(0), start: '09:30', end: '10:30', purpose: 'Standup overflow', status: 'confirmed', organizer: 'Tamer Sobhy', attendees: 4 },
  { spaceId: 'olive', date: day(0), start: '13:00', end: '14:00', purpose: 'Recruiter sync', status: 'confirmed', organizer: 'Dina Hafez', attendees: 2 },
  { spaceId: 'pod-2a', date: day(0), start: '14:00', end: '15:00', purpose: 'Focus block', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 1 },
  { spaceId: 'pod-2b', date: day(0), start: '10:00', end: '12:00', purpose: 'Deep work', status: 'confirmed', organizer: 'Omar Zaki', attendees: 1 },
  { spaceId: 'desk-4-118', date: day(0), start: '09:00', end: '17:00', purpose: 'Focus day', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 1 },
  { spaceId: 'desk-4-122', date: day(0), start: '09:00', end: '17:00', purpose: 'Desk for the day', status: 'checked-in', organizer: 'Yara Sabry', attendees: 1, checkedInAt: at('08:51') },
  { spaceId: 'maple', date: day(0), start: '11:30', end: '12:30', purpose: 'Platform review', status: 'confirmed', organizer: 'Ziad Morsi', attendees: 6 },
  { spaceId: 'maple', date: day(0), start: '15:00', end: '16:00', purpose: 'Budget checkpoint', status: 'confirmed', organizer: 'Tarek Aziz', attendees: 5 },
  { spaceId: 'studio-4', date: day(0), start: '09:00', end: '10:00', purpose: 'Content planning', status: 'confirmed', organizer: 'Farah Nabil', attendees: 4 },
  { spaceId: 'studio-4', date: day(0), start: '13:30', end: '14:30', purpose: 'Campaign review', status: 'confirmed', organizer: 'Amira Shafik', attendees: 5 },
  { spaceId: 'lotus', date: day(0), start: '16:00', end: '17:00', purpose: 'Vendor demo', status: 'confirmed', organizer: 'Hana Youssef', attendees: 5 },
  { spaceId: 'orchid', date: day(0), start: '16:00', end: '17:00', purpose: 'Pipeline review', status: 'pending', organizer: 'Khaled Nour', attendees: 8 },
  { spaceId: 'boardroom', date: day(0), start: '11:00', end: '13:00', purpose: 'Board lunch', status: 'pending', organizer: 'Noura Sami', attendees: 10 },
  { spaceId: 'atrium', date: day(0), start: '09:00', end: '11:00', purpose: 'Onboarding week', status: 'pending', organizer: 'Lina Haddad', attendees: 25 },
  { spaceId: 'studio-3', date: day(0), start: '15:30', end: '16:30', purpose: 'Partnership intro', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 4 },

  { spaceId: 'studio-3', date: day(1), start: '11:00', end: '12:00', purpose: 'Portfolio review', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 3 },
  { spaceId: 'cedar', date: day(1), start: '09:30', end: '11:00', purpose: 'Retro', status: 'confirmed', organizer: 'Karim Fouad', attendees: 6 },
  { spaceId: 'desk-4-118', date: day(1), start: '09:00', end: '17:00', purpose: 'Focus day', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 1 },
  { spaceId: 'maple', date: day(1), start: '15:00', end: '16:30', purpose: 'Security review', status: 'confirmed', organizer: 'Adel Rashid', attendees: 7 },
  { spaceId: 'lab', date: day(1), start: '09:00', end: '11:00', purpose: 'Research readout', status: 'confirmed', organizer: 'Reem Othman', attendees: 12 },
  { spaceId: 'pod-2a', date: day(1), start: '13:00', end: '15:00', purpose: 'Writing block', status: 'confirmed', organizer: 'Farah Nabil', attendees: 1 },

  { spaceId: 'cedar', date: day(2), start: '10:00', end: '11:30', purpose: 'Sprint planning', status: 'confirmed', organizer: 'Karim Fouad', attendees: 5 },
  { spaceId: 'skyline', date: day(2), start: '09:00', end: '12:00', purpose: 'Leadership offsite', status: 'pending', organizer: 'Noura Sami', attendees: 18 },
  { spaceId: 'desk-4-118', date: day(2), start: '09:00', end: '17:00', purpose: 'Focus day', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 1 },
  { spaceId: 'jasmine', date: day(2), start: '14:00', end: '15:00', purpose: 'One to one', status: 'confirmed', organizer: 'Lina Haddad', attendees: 2 },

  { spaceId: 'studio-3', date: day(-1), start: '10:00', end: '11:00', purpose: 'Design sync', status: 'checked-in', organizer: 'Sara Ahmed', attendees: 3, checkedInAt: at('10:01', -1) },
  { spaceId: 'cedar', date: day(-1), start: '14:00', end: '15:00', purpose: 'Incident review', status: 'checked-in', organizer: 'Sami Kamal', attendees: 6, checkedInAt: at('14:04', -1) },
  { spaceId: 'pod-2b', date: day(-1), start: '09:00', end: '11:00', purpose: 'Deep work', status: 'checked-in', organizer: 'Omar Zaki', attendees: 1, checkedInAt: at('09:00', -1) },
];

const eventHolds: Hold[] = EVENTS.filter((event) => event.spaceId && event.status === 'published').map(
  (event) => ({
    spaceId: event.spaceId,
    date: event.date,
    start: event.start,
    end: event.end,
    purpose: event.title,
    status: 'confirmed' as const,
    organizer: event.host,
    attendees: event.going.length,
    eventId: event.id,
  }),
);

const visitHolds: Hold[] = VISITS.filter((visit) => visit.spaceId && visit.status !== 'cancelled').map(
  (visit) => ({
    spaceId: visit.spaceId,
    date: visit.date,
    start: visit.time,
    end: `${String(Number(visit.time.slice(0, 2)) + 1).padStart(2, '0')}${visit.time.slice(2)}`,
    purpose: `${visit.purpose} — ${visit.company}`,
    status: 'confirmed' as const,
    organizer: visit.host,
    attendees: 4,
  }),
);

export const BOOKINGS: New<Booking>[] = [
  ...DESK_AND_ROOM_HOLDS,
  ...eventHolds,
  ...visitHolds,
].map((hold) => {
  const space = spaceById.get(hold.spaceId ?? '');
  return {
    ...hold,
    space: space?.name ?? 'Riyadh HQ',
    level: space?.level ?? 'Level 1',
    capacity: space?.capacity ?? 8,
  };
});

export const MEETINGS: New<Meeting>[] = [
  { title: 'Design sync', space: 'Studio 3', level: 'Level 2', start: minutesFromNow(25), end: minutesFromNow(85), attendees: ['SA', 'RK', 'RO'], status: 'confirmed' },
  { title: 'Lunch & Learn: Design Systems', space: 'Innovation Lab', level: 'Level 3', start: minutesFromNow(85), end: minutesFromNow(145), attendees: ['SA', 'RK', 'YS', 'MF'], status: 'confirmed' },
  { title: 'Client visit — Northwind', space: 'Orchid', level: 'Level 5', start: minutesFromNow(150), end: minutesFromNow(210), attendees: ['SA', 'HY'], status: 'confirmed' },
  { title: 'Partnership intro — Vertex Labs', space: 'Studio 3', level: 'Level 2', start: minutesFromNow(215), end: minutesFromNow(275), attendees: ['SA', 'HY'], status: 'confirmed' },
  { title: 'A little focus time', space: 'Pod 2-A', level: 'Level 2', start: minutesFromNow(280), end: minutesFromNow(340), attendees: ['SA'], status: 'tentative' },
];

export const BADGES: New<Badge>[] = [
  { number: '101' },
  { number: '102', visitId: 'seed_3' },
  { number: '103' },
  { number: '104', visitId: 'seed_2' },
  { number: '105' },
  { number: '106' },
  { number: '107' },
  { number: '108' },
  { number: '109' },
  { number: '110' },
  { number: 'VIP-01', visitId: 'seed_4' },
  { number: 'VIP-02' },
];

export const DELIVERIES: New<Delivery>[] = [
  { recipient: 'Sara Ahmed', carrier: 'DHL', tracking: '7850 0212 3456', collected: false },
  { recipient: 'Karim Fouad', carrier: 'Aramex', tracking: '4471 9930 1122', collected: false },
  { recipient: 'Rana Khalil', carrier: 'SMSA', tracking: '2039 8871 4520', collected: false },
  { recipient: 'Ziad Morsi', carrier: 'DHL', tracking: '6612 3390 8874', collected: false },
  { recipient: 'Salma Gaber', carrier: 'Aramex', tracking: '1180 5567 2341', collected: false },
  { recipient: 'Nadia Salem', carrier: 'FedEx', tracking: '9920 4417 8830', collected: true },
  { recipient: 'Hassan Iqbal', carrier: 'Alpine Foods', tracking: 'AF-2291', collected: true },
  { recipient: 'Bassem Riad', carrier: 'SMSA', tracking: '7741 2098 6633', collected: true },
];

export const ORDERS: New<Order>[] = [
  {
    item: 'Flat White',
    options: 'Large · Oat · Extra shot',
    destination: 'Studio 3 · Level 2',
    price: 23,
    status: 'on-the-way',
    lines: [{ menuItemId: 'flat-white', name: 'Flat White', options: 'Large · Oat · Extra shot', unitPrice: 23, quantity: 1 }],
  },
  {
    item: 'Karak Tea',
    options: 'Regular · Extra cardamom',
    destination: 'Cedar · Level 3',
    price: 36,
    status: 'preparing',
    lines: [{ menuItemId: 'karak-tea', name: 'Karak Tea', options: 'Regular · Extra cardamom', unitPrice: 12, quantity: 3 }],
  },
  {
    item: 'Mezze Platter',
    options: 'For four',
    destination: 'Orchid · Level 5',
    price: 140,
    status: 'placed',
    note: 'Client lunch — please plate it properly.',
    lines: [{ menuItemId: 'mezze-platter', name: 'Mezze Platter', options: 'For four', unitPrice: 140, quantity: 1 }],
  },
  {
    item: 'Cortado',
    options: 'Regular',
    destination: 'Desk 4-122',
    price: 18,
    status: 'on-the-way',
    lines: [{ menuItemId: 'cortado', name: 'Cortado', options: 'Regular', unitPrice: 18, quantity: 1 }],
  },
  {
    item: 'Jasmine Green Tea',
    options: 'Regular',
    destination: 'Desk 4-118',
    price: 21,
    status: 'delivered',
    lines: [
      { menuItemId: 'green-tea', name: 'Jasmine Green Tea', options: 'Regular', unitPrice: 9, quantity: 1 },
      { menuItemId: 'blueberry-muffin', name: 'Blueberry Muffin', options: 'Warmed', unitPrice: 12, quantity: 1 },
    ],
  },
  {
    item: 'Iced Latte',
    options: 'Large · Almond',
    destination: 'Innovation Lab · Level 3',
    price: 50,
    status: 'delivered',
    lines: [{ menuItemId: 'iced-latte', name: 'Iced Latte', options: 'Large · Almond', unitPrice: 25, quantity: 2 }],
  },
  {
    item: 'Chicken Shawarma Bowl',
    options: 'Spicy · No pickles',
    destination: 'Desk 4-118',
    price: 45,
    status: 'delivered',
    lines: [{ menuItemId: 'shawarma-bowl', name: 'Chicken Shawarma Bowl', options: 'Spicy · No pickles', unitPrice: 45, quantity: 1 }],
  },
  {
    item: 'Date Smoothie',
    options: 'Regular',
    destination: 'Roof Garden · Level 7',
    price: 28,
    status: 'delivered',
    lines: [{ menuItemId: 'date-smoothie', name: 'Date Smoothie', options: 'Regular', unitPrice: 28, quantity: 1 }],
  },
];

export const TICKETS: New<Ticket>[] = [
  { subject: 'Projector not connecting in Orchid', category: 'AV', location: 'Level 5 · Orchid', priority: 'high', status: 'in-progress' },
  { subject: 'Level 4 north wing feels warm', category: 'Comfort', location: 'Level 4', priority: 'medium', status: 'open' },
  { subject: 'Badge reader rejecting on Level 6', category: 'Access', location: 'Level 6 · Lift lobby', priority: 'high', status: 'in-progress' },
  { subject: 'Coffee machine leaking in the café', category: 'Catering', location: 'Level 1 · Smart Café', priority: 'medium', status: 'open' },
  { subject: 'Standing desk motor jammed', category: 'Furniture', location: 'Level 4 · Desk 4-120', priority: 'low', status: 'in-progress' },
  { subject: 'Wi-Fi drops in the Roof Garden', category: 'Network', location: 'Level 7', priority: 'medium', status: 'open' },
  { subject: 'Whiteboard markers all dry in Cedar', category: 'Supplies', location: 'Level 3 · Cedar', priority: 'low', status: 'open' },
  { subject: 'Forum microphone feedback', category: 'AV', location: 'Level 1 · The Forum', priority: 'high', status: 'resolved' },
  { subject: 'Parking barrier slow to lift', category: 'Access', location: 'Basement 1', priority: 'low', status: 'resolved' },
  { subject: 'Recycling bins not collected', category: 'Cleaning', location: 'Level 2', priority: 'low', status: 'resolved' },
];

export const TASKS: New<Task>[] = [
  { title: 'Approve Northwind visit agenda', due: 'Today · 12:00', effort: 'quick', done: false },
  { title: 'Review Q3 space utilisation', due: 'Today · 16:00', effort: 'focused', done: false },
  { title: 'Confirm Lunch & Learn catering headcount', due: 'Today · 11:00', effort: 'quick', done: false },
  { title: 'Draft the design system talk outline', due: 'Today · 12:00', effort: 'deep', done: false },
  { title: 'Send Daniel the interview brief', due: 'Tomorrow · 09:00', effort: 'quick', done: false },
  { title: 'Pick the Tech Summit breakout tracks', due: 'Tomorrow · 15:00', effort: 'focused', done: false },
  { title: 'Reply to Vertex Labs on the pilot scope', due: 'Tomorrow', effort: 'focused', done: false },
  { title: 'Sign off signage refresh', due: 'Yesterday', effort: 'quick', done: true },
  { title: 'Book the Q4 offsite space', due: 'Yesterday', effort: 'quick', done: true },
  { title: 'Close out the hack day retro notes', due: 'Yesterday', effort: 'focused', done: true },
];

export const NOTIFICATIONS: New<Notification>[] = [
  { title: 'Layla Nasser pre-registered', body: 'Arriving 13:00 · Orchid, Level 5', product: 'VisitFlow', read: false },
  { title: 'Lunch & Learn starts in an hour', body: 'Innovation Lab · 14 going, 2 waiting', product: 'Gather', read: false },
  { title: 'Studio 3 is ready', body: 'Comfort set for your 10:00 sync', product: 'Atmosphere', read: false },
  { title: 'Two people joined your waitlist', body: 'Design Systems at Scale is now full', product: 'Gather', read: false },
  { title: 'Ingrid Sørensen has checked in', body: 'VIP · Lotus, Level 5 · badge VIP-01', product: 'VisitFlow', read: false },
  { title: 'Your flat white is on the way', body: 'Delivering to Studio 3', product: 'Nourish', read: true },
  { title: 'Orchid needs your approval', body: 'Khaled Nour requested 16:00–17:00', product: 'SpaceOS', read: true },
  { title: 'Q4 All-Hands is tomorrow', body: 'The Forum · 14:00 · attendance expected', product: 'Gather', read: true },
  { title: 'Projector ticket picked up', body: 'AV team is on Level 5 now', product: 'Resolve', read: true },
  { title: 'Desk 4-120 is offline', body: 'Monitor arm replacement — back Thursday', product: 'SpaceOS', read: true },
];
