import { shiftDay, todayKey } from './format';
import type { Entity } from './store';
import type {
  Badge,
  Booking,
  Delivery,
  GatherEvent,
  Meeting,
  Notification,
  Order,
  Post,
  Space,
  Task,
  Ticket,
  Tribe,
  Visit,
} from './data';

type New<T> = Omit<T, keyof Entity>;

type Hold = Omit<New<Booking>, 'space' | 'level' | 'capacity'>;

type EventSeed = Omit<New<GatherEvent>, 'location'> & { location?: string };

const day = (offset: number): string => shiftDay(todayKey(), offset);

const at = (clock: string, offset = 0): string => {
  const [hours, minutes] = clock.split(':').map(Number);
  const date = new Date(`${day(offset)}T00:00:00`);
  date.setHours(hours, minutes, 0, 0);
  return date.toISOString();
};

const minutesFromNow = (offset: number): string => {
  const date = new Date();
  date.setMinutes(date.getMinutes() + offset, 0, 0);
  return date.toISOString();
};

const hoursAgo = (offset: number): string => minutesFromNow(-offset * 60);

export const PEOPLE = [
  { name: 'Sara Ahmed', role: 'Product Design Lead', team: 'Design' },
  { name: 'Karim Fouad', role: 'Engineering Manager', team: 'Engineering' },
  { name: 'Nadia Salem', role: 'Staff Engineer', team: 'Engineering' },
  { name: 'Hana Youssef', role: 'Partnerships Lead', team: 'Commercial' },
  { name: 'Omar Zaki', role: 'Data Scientist', team: 'Data' },
  { name: 'Lina Haddad', role: 'People Partner', team: 'People' },
  { name: 'Yousef Mansour', role: 'Facilities Manager', team: 'Workplace' },
  { name: 'Rana Khalil', role: 'Brand Designer', team: 'Design' },
  { name: 'Tarek Aziz', role: 'Finance Analyst', team: 'Finance' },
  { name: 'Mona Darwish', role: 'Wellness Coach', team: 'People' },
  { name: 'Adel Rashid', role: 'Security Lead', team: 'Workplace' },
  { name: 'Farah Nabil', role: 'Content Strategist', team: 'Marketing' },
  { name: 'Bassem Riad', role: 'IT Support Engineer', team: 'IT' },
  { name: 'Dina Hafez', role: 'Technical Recruiter', team: 'People' },
  { name: 'Ziad Morsi', role: 'Solutions Architect', team: 'Engineering' },
  { name: 'Salma Gaber', role: 'Community Manager', team: 'Marketing' },
  { name: 'Noura Sami', role: 'Chief of Staff', team: 'Executive' },
  { name: 'Hassan Iqbal', role: 'Café Manager', team: 'Workplace' },
  { name: 'Maya Fahmy', role: 'Product Manager', team: 'Product' },
  { name: 'Tamer Sobhy', role: 'QA Lead', team: 'Engineering' },
  { name: 'Reem Othman', role: 'UX Researcher', team: 'Design' },
  { name: 'Fadi Barakat', role: 'Account Executive', team: 'Commercial' },
  { name: 'Laila Mostafa', role: 'Legal Counsel', team: 'Legal' },
  { name: 'Sami Kamal', role: 'DevOps Engineer', team: 'Engineering' },
  { name: 'Amira Shafik', role: 'Marketing Manager', team: 'Marketing' },
  { name: 'Khaled Nour', role: 'Sales Director', team: 'Commercial' },
  { name: 'Yara Sabry', role: 'Front-end Engineer', team: 'Engineering' },
  { name: 'Waleed Tantawy', role: 'Procurement Lead', team: 'Finance' },
];

export const SPACES: Array<New<Space> & { id: string }> = [
  { id: 'atrium', name: 'The Atrium', kind: 'Training', level: 'Level 1', capacity: 30, amenities: ['Display', 'Catering', 'Daylight'], utilisation: 88, offline: false, approval: true },
  { id: 'forum', name: 'The Forum', kind: 'Training', level: 'Level 1', capacity: 120, amenities: ['Stage', 'Video', 'Display', 'Catering'], utilisation: 61, offline: false, approval: true },
  { id: 'studio-3', name: 'Studio 3', kind: 'Meeting room', level: 'Level 2', capacity: 8, amenities: ['Video', 'Whiteboard', 'Display'], utilisation: 64, offline: false, approval: false },
  { id: 'studio-4', name: 'Studio 4', kind: 'Meeting room', level: 'Level 2', capacity: 6, amenities: ['Video', 'Whiteboard'], utilisation: 47, offline: false, approval: false },
  { id: 'pod-2a', name: 'Pod 2-A', kind: 'Focus pod', level: 'Level 2', capacity: 1, amenities: ['Soundproof'], utilisation: 71, offline: false, approval: false },
  { id: 'pod-2b', name: 'Pod 2-B', kind: 'Focus pod', level: 'Level 2', capacity: 1, amenities: ['Soundproof'], utilisation: 34, offline: false, approval: false },
  { id: 'cedar', name: 'Cedar', kind: 'Meeting room', level: 'Level 3', capacity: 6, amenities: ['Display', 'Whiteboard'], utilisation: 52, offline: false, approval: false },
  { id: 'jasmine', name: 'Jasmine', kind: 'Huddle', level: 'Level 3', capacity: 4, amenities: ['Display'], utilisation: 41, offline: false, approval: false },
  { id: 'olive', name: 'Olive', kind: 'Huddle', level: 'Level 3', capacity: 4, amenities: ['Whiteboard'], utilisation: 29, offline: false, approval: false },
  { id: 'lab', name: 'Innovation Lab', kind: 'Training', level: 'Level 3', capacity: 24, amenities: ['Whiteboard', 'Display', 'Daylight'], utilisation: 57, offline: false, approval: false },
  { id: 'maple', name: 'Maple', kind: 'Meeting room', level: 'Level 4', capacity: 8, amenities: ['Video', 'Display'], utilisation: 66, offline: false, approval: false },
  { id: 'desk-4-118', name: 'Desk 4-118', kind: 'Desk', level: 'Level 4', capacity: 1, amenities: ['Dual monitors', 'Daylight'], utilisation: 30, offline: false, approval: false },
  { id: 'desk-4-120', name: 'Desk 4-120', kind: 'Desk', level: 'Level 4', capacity: 1, amenities: ['Standing desk'], utilisation: 12, offline: true, approval: false, note: 'Monitor arm replacement — back Thursday.' },
  { id: 'desk-4-122', name: 'Desk 4-122', kind: 'Desk', level: 'Level 4', capacity: 1, amenities: ['Dual monitors'], utilisation: 44, offline: false, approval: false },
  { id: 'orchid', name: 'Orchid', kind: 'Meeting room', level: 'Level 5', capacity: 12, amenities: ['Video', 'Display', 'Catering'], utilisation: 78, offline: false, approval: true },
  { id: 'lotus', name: 'Lotus', kind: 'Meeting room', level: 'Level 5', capacity: 10, amenities: ['Video', 'Whiteboard', 'Daylight'], utilisation: 55, offline: false, approval: false },
  { id: 'boardroom', name: 'The Boardroom', kind: 'Meeting room', level: 'Level 6', capacity: 14, amenities: ['Video', 'Catering', 'Daylight'], utilisation: 23, offline: false, approval: true },
  { id: 'skyline', name: 'Skyline Lounge', kind: 'Training', level: 'Level 6', capacity: 40, amenities: ['Display', 'Catering', 'Daylight'], utilisation: 49, offline: false, approval: true },
  { id: 'roof-garden', name: 'Roof Garden', kind: 'Training', level: 'Level 7', capacity: 60, amenities: ['Daylight', 'Catering'], utilisation: 36, offline: false, approval: true },
];

const spaceById = new Map(SPACES.map((space) => [space.id, space]));

const where = (spaceId: string): string => {
  const space = spaceById.get(spaceId);
  return space ? `${space.name} · ${space.level}` : 'Riyadh HQ';
};

const EVENT_SEED: Array<EventSeed & { id: string }> = [
  {
    id: 'ev-townhall-q3',
    title: 'Q3 All-Hands',
    category: 'Town hall',
    mode: 'Hybrid',
    date: day(-7),
    start: '14:00',
    end: '15:30',
    spaceId: 'forum',
    host: 'Noura Sami',
    team: 'Executive',
    capacity: 120,
    price: 0,
    required: true,
    status: 'published',
    summary: 'Quarterly numbers, the roadmap reset, and the people awards. Streamed for anyone off site.',
    tags: ['Company', 'Strategy'],
    going: ['Sara Ahmed', 'Karim Fouad', 'Nadia Salem', 'Hana Youssef', 'Omar Zaki', 'Lina Haddad', 'Yousef Mansour', 'Rana Khalil', 'Tarek Aziz', 'Adel Rashid', 'Farah Nabil', 'Ziad Morsi', 'Noura Sami', 'Maya Fahmy', 'Reem Othman', 'Laila Mostafa', 'Amira Shafik', 'Khaled Nour'],
    waitlist: [],
  },
  {
    id: 'ev-hack-day',
    title: 'Internal Hack Day',
    category: 'Learning',
    mode: 'In person',
    date: day(-4),
    start: '09:00',
    end: '17:00',
    spaceId: 'lab',
    host: 'Karim Fouad',
    team: 'Engineering',
    capacity: 24,
    price: 0,
    required: false,
    status: 'published',
    summary: 'One day, one prototype. Teams of three, demos at four, the winner ships next sprint.',
    tags: ['Engineering', 'Prototyping'],
    going: ['Karim Fouad', 'Nadia Salem', 'Ziad Morsi', 'Sami Kamal', 'Yara Sabry', 'Tamer Sobhy', 'Omar Zaki', 'Maya Fahmy', 'Sara Ahmed', 'Bassem Riad'],
    waitlist: [],
  },
  {
    id: 'ev-coffee-tasting',
    title: 'Single-Origin Coffee Tasting',
    category: 'Social',
    mode: 'In person',
    date: day(-1),
    start: '15:00',
    end: '16:00',
    spaceId: 'atrium',
    host: 'Hassan Iqbal',
    team: 'Workplace',
    capacity: 24,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Four roasts from three farms, poured side by side. Bring a cup and an opinion.',
    tags: ['Coffee', 'Tasting'],
    going: ['Hassan Iqbal', 'Sara Ahmed', 'Rana Khalil', 'Farah Nabil', 'Salma Gaber', 'Reem Othman', 'Dina Hafez', 'Amira Shafik', 'Tarek Aziz'],
    waitlist: [],
  },
  {
    id: 'ev-yoga',
    title: 'Sunrise Yoga Flow',
    category: 'Wellness',
    mode: 'In person',
    date: day(0),
    start: '08:00',
    end: '09:00',
    spaceId: 'roof-garden',
    host: 'Mona Darwish',
    team: 'People',
    capacity: 24,
    price: 0,
    required: false,
    status: 'published',
    summary: 'A slow start on the roof before the inbox opens. Mats and towels are laid out for you.',
    tags: ['Wellness', 'Movement'],
    going: ['Mona Darwish', 'Sara Ahmed', 'Lina Haddad', 'Reem Othman', 'Rana Khalil', 'Dina Hafez', 'Yara Sabry', 'Amira Shafik', 'Maya Fahmy', 'Salma Gaber', 'Laila Mostafa'],
    waitlist: [],
  },
  {
    id: 'ev-lunch-learn',
    title: 'Lunch & Learn: Design Systems at Scale',
    category: 'Learning',
    mode: 'Hybrid',
    date: day(0),
    start: '12:30',
    end: '13:30',
    spaceId: 'lab',
    host: 'Sara Ahmed',
    team: 'Design',
    capacity: 24,
    price: 0,
    required: false,
    status: 'published',
    summary: 'How the token layer cut our design-to-ship time in half, and the three places it still hurts.',
    tags: ['Design', 'Tokens', 'Lunch provided'],
    going: ['Sara Ahmed', 'Rana Khalil', 'Reem Othman', 'Yara Sabry', 'Maya Fahmy', 'Nadia Salem', 'Farah Nabil', 'Ziad Morsi', 'Tamer Sobhy', 'Karim Fouad', 'Salma Gaber', 'Bassem Riad', 'Omar Zaki', 'Dina Hafez'],
    waitlist: ['Fadi Barakat', 'Waleed Tantawy'],
  },
  {
    id: 'ev-new-joiner',
    title: 'New Joiner Welcome',
    category: 'Culture',
    mode: 'In person',
    date: day(0),
    start: '16:00',
    end: '17:30',
    spaceId: 'skyline',
    host: 'Lina Haddad',
    team: 'People',
    capacity: 40,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Nine people joined this month. Come put faces to the names over something cold.',
    tags: ['Culture', 'Onboarding'],
    going: ['Lina Haddad', 'Dina Hafez', 'Noura Sami', 'Sara Ahmed', 'Karim Fouad', 'Hana Youssef', 'Salma Gaber', 'Yousef Mansour', 'Maya Fahmy', 'Amira Shafik', 'Fadi Barakat', 'Khaled Nour'],
    waitlist: [],
  },
  {
    id: 'ev-townhall-q4',
    title: 'Q4 All-Hands',
    category: 'Town hall',
    mode: 'Hybrid',
    date: day(1),
    start: '14:00',
    end: '15:30',
    spaceId: 'forum',
    host: 'Noura Sami',
    team: 'Executive',
    capacity: 120,
    price: 0,
    required: true,
    status: 'published',
    summary: 'Where we landed the quarter, what changes in January, and twenty minutes of open questions.',
    tags: ['Company', 'Strategy'],
    going: ['Noura Sami', 'Sara Ahmed', 'Karim Fouad', 'Hana Youssef', 'Nadia Salem', 'Omar Zaki', 'Lina Haddad', 'Tarek Aziz', 'Rana Khalil', 'Adel Rashid', 'Maya Fahmy', 'Ziad Morsi', 'Laila Mostafa', 'Khaled Nour', 'Amira Shafik', 'Waleed Tantawy'],
    waitlist: [],
  },
  {
    id: 'ev-run-club',
    title: 'Riyadh Run Club',
    category: 'Wellness',
    mode: 'In person',
    date: day(1),
    start: '18:00',
    end: '19:30',
    location: 'Wadi Hanifah trail · meet at reception',
    host: 'Tamer Sobhy',
    team: 'Engineering',
    capacity: 20,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Five kilometres along the wadi at an easy pace. Nobody gets left behind, nobody gets timed.',
    tags: ['Running', 'Outdoors'],
    going: ['Tamer Sobhy', 'Sami Kamal', 'Yara Sabry', 'Mona Darwish', 'Omar Zaki', 'Fadi Barakat', 'Karim Fouad'],
    waitlist: [],
  },
  {
    id: 'ev-latte-art',
    title: 'Barista Workshop: Latte Art',
    category: 'Social',
    mode: 'In person',
    date: day(2),
    start: '16:00',
    end: '17:30',
    spaceId: 'atrium',
    host: 'Hassan Iqbal',
    team: 'Workplace',
    capacity: 12,
    price: 75,
    required: false,
    status: 'published',
    summary: 'Pour a rosetta that holds its shape. Beans to take home, and the milk is on us.',
    tags: ['Coffee', 'Workshop'],
    going: ['Hassan Iqbal', 'Rana Khalil', 'Reem Othman', 'Salma Gaber', 'Farah Nabil', 'Dina Hafez', 'Amira Shafik', 'Maya Fahmy', 'Yara Sabry', 'Lina Haddad', 'Sara Ahmed', 'Mona Darwish'],
    waitlist: ['Tarek Aziz', 'Bassem Riad', 'Nadia Salem'],
  },
  {
    id: 'ev-ai-guild',
    title: 'AI Guild: Agents in Production',
    category: 'Learning',
    mode: 'Hybrid',
    date: day(3),
    start: '11:00',
    end: '12:30',
    spaceId: 'forum',
    host: 'Ziad Morsi',
    team: 'Engineering',
    capacity: 60,
    price: 0,
    required: false,
    status: 'published',
    summary: 'What broke when we put agents in front of real customers, and the guardrails that held.',
    tags: ['AI', 'Architecture'],
    going: ['Ziad Morsi', 'Nadia Salem', 'Omar Zaki', 'Sami Kamal', 'Karim Fouad', 'Tamer Sobhy', 'Yara Sabry', 'Maya Fahmy', 'Sara Ahmed', 'Bassem Riad', 'Reem Othman'],
    waitlist: [],
  },
  {
    id: 'ev-board-games',
    title: 'Board Game Night',
    category: 'Social',
    mode: 'In person',
    date: day(3),
    start: '17:30',
    end: '20:00',
    spaceId: 'skyline',
    host: 'Salma Gaber',
    team: 'Marketing',
    capacity: 30,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Catan, Codenames and a worryingly competitive Uno table. Pizza lands at six.',
    tags: ['Games', 'Food'],
    going: ['Salma Gaber', 'Farah Nabil', 'Bassem Riad', 'Tamer Sobhy', 'Yara Sabry', 'Sami Kamal', 'Dina Hafez', 'Fadi Barakat'],
    waitlist: [],
  },
  {
    id: 'ev-first-aid',
    title: 'First Aid Certification',
    category: 'Wellness',
    mode: 'In person',
    date: day(4),
    start: '09:00',
    end: '13:00',
    spaceId: 'lab',
    host: 'Adel Rashid',
    team: 'Workplace',
    capacity: 16,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Certified by the Red Crescent, valid three years. Half a day, and you leave able to help.',
    tags: ['Safety', 'Certification'],
    going: ['Adel Rashid', 'Yousef Mansour', 'Mona Darwish', 'Hassan Iqbal', 'Lina Haddad', 'Bassem Riad', 'Waleed Tantawy', 'Tarek Aziz', 'Khaled Nour', 'Laila Mostafa', 'Amira Shafik', 'Omar Zaki', 'Sami Kamal', 'Dina Hafez', 'Fadi Barakat', 'Noura Sami'],
    waitlist: ['Sara Ahmed', 'Rana Khalil', 'Maya Fahmy'],
  },
  {
    id: 'ev-vendor-fair',
    title: 'Workplace Vendor Fair',
    category: 'Culture',
    mode: 'In person',
    date: day(5),
    start: '11:00',
    end: '15:00',
    spaceId: 'atrium',
    host: 'Waleed Tantawy',
    team: 'Finance',
    capacity: 30,
    price: 0,
    required: false,
    status: 'cancelled',
    summary: 'Pulled back to January — three of the six suppliers could not make the new date.',
    tags: ['Procurement'],
    going: ['Waleed Tantawy', 'Yousef Mansour', 'Tarek Aziz'],
    waitlist: [],
  },
  {
    id: 'ev-design-crit',
    title: 'Open Design Critique',
    category: 'Learning',
    mode: 'In person',
    date: day(7),
    start: '10:00',
    end: '11:30',
    spaceId: 'studio-3',
    host: 'Reem Othman',
    team: 'Design',
    capacity: 8,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Bring one screen you are unsure about. Kind, specific, and no deck required.',
    tags: ['Design', 'Feedback'],
    going: ['Reem Othman', 'Sara Ahmed', 'Rana Khalil', 'Maya Fahmy', 'Yara Sabry', 'Farah Nabil', 'Salma Gaber', 'Amira Shafik'],
    waitlist: ['Nadia Salem', 'Dina Hafez'],
  },
  {
    id: 'ev-culture-day',
    title: 'Culture Day Potluck',
    category: 'Culture',
    mode: 'In person',
    date: day(9),
    start: '12:00',
    end: '14:30',
    spaceId: 'atrium',
    host: 'Salma Gaber',
    team: 'Marketing',
    capacity: 30,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Twenty-two nationalities, one very long table. Bring a dish that means something to you.',
    tags: ['Culture', 'Food'],
    going: ['Salma Gaber', 'Lina Haddad', 'Hassan Iqbal', 'Farah Nabil', 'Dina Hafez', 'Amira Shafik', 'Khaled Nour', 'Laila Mostafa', 'Reem Othman', 'Rana Khalil', 'Waleed Tantawy', 'Fadi Barakat', 'Mona Darwish'],
    waitlist: [],
  },
  {
    id: 'ev-security-brief',
    title: 'Security Awareness Briefing',
    category: 'Learning',
    mode: 'Virtual',
    date: day(10),
    start: '10:00',
    end: '11:00',
    location: 'Streamed — joining link in the invite',
    host: 'Adel Rashid',
    team: 'Workplace',
    capacity: 120,
    price: 0,
    required: true,
    status: 'published',
    summary: 'The annual one. Phishing, tailgating, and what to do in the ninety seconds after a mistake.',
    tags: ['Security', 'Mandatory'],
    going: ['Adel Rashid', 'Bassem Riad', 'Laila Mostafa', 'Noura Sami', 'Karim Fouad', 'Sami Kamal', 'Tarek Aziz', 'Waleed Tantawy', 'Ziad Morsi'],
    waitlist: [],
  },
  {
    id: 'ev-summit',
    title: 'Dixels Tech Summit 2026',
    category: 'Learning',
    mode: 'Hybrid',
    date: day(14),
    start: '09:00',
    end: '17:00',
    spaceId: 'forum',
    host: 'Karim Fouad',
    team: 'Engineering',
    capacity: 120,
    price: 0,
    required: false,
    status: 'published',
    summary: 'Our flagship day: two keynotes, eight breakouts on platform, data and design, and a long lunch.',
    tags: ['Flagship', 'Keynote', 'Networking'],
    going: ['Karim Fouad', 'Nadia Salem', 'Ziad Morsi', 'Sami Kamal', 'Yara Sabry', 'Tamer Sobhy', 'Omar Zaki', 'Sara Ahmed', 'Rana Khalil', 'Reem Othman', 'Maya Fahmy', 'Bassem Riad', 'Noura Sami', 'Hana Youssef', 'Farah Nabil', 'Salma Gaber', 'Amira Shafik', 'Khaled Nour', 'Fadi Barakat', 'Dina Hafez', 'Lina Haddad', 'Mona Darwish'],
    waitlist: [],
  },
  {
    id: 'ev-wellness-week',
    title: 'Wellness Week Kickoff',
    category: 'Wellness',
    mode: 'In person',
    date: day(16),
    start: '08:30',
    end: '10:00',
    spaceId: 'roof-garden',
    host: 'Mona Darwish',
    team: 'People',
    capacity: 60,
    price: 0,
    required: false,
    status: 'draft',
    summary: 'Still pinning down the physio and the smoothie cart before this one goes out to everyone.',
    tags: ['Wellness'],
    going: ['Mona Darwish'],
    waitlist: [],
  },
];

const EVENT_TRIBE: Record<string, string> = {
  'ev-hack-day': 'tr-tech-talks',
  'ev-ai-guild': 'tr-tech-talks',
  'ev-summit': 'tr-tech-talks',
  'ev-lunch-learn': 'tr-design-guild',
  'ev-design-crit': 'tr-design-guild',
  'ev-run-club': 'tr-run-club',
  'ev-yoga': 'tr-mindful',
  'ev-wellness-week': 'tr-mindful',
  'ev-coffee-tasting': 'tr-coffee',
  'ev-latte-art': 'tr-coffee',
  'ev-board-games': 'tr-board-games',
  'ev-new-joiner': 'tr-new-joiners',
};

export const EVENTS = EVENT_SEED.map((event) => ({
  ...event,
  location: event.location ?? where(event.spaceId ?? ''),
  tribeId: EVENT_TRIBE[event.id],
}));

export const VISITS: New<Visit>[] = [
  { guest: 'Layla Nasser', company: 'Northwind', host: 'Sara Ahmed', date: day(0), time: '13:00', purpose: 'Quarterly review', status: 'pre-registered', email: 'layla.nasser@northwind.com', kind: 'VIP', spaceId: 'orchid', location: where('orchid'), parking: true, code: 'VF-4180' },
  { guest: 'Omar Haddad', company: 'Vertex Labs', host: 'Sara Ahmed', date: day(0), time: '15:30', purpose: 'Partnership intro', status: 'invited', email: 'o.haddad@vertexlabs.io', kind: 'Guest', spaceId: 'studio-3', location: where('studio-3'), parking: false, code: 'VF-7723' },
  { guest: 'Mei Chen', company: 'Aurora', host: 'Karim Fouad', date: day(0), time: '09:15', purpose: 'Onsite audit', status: 'checked-in', email: 'mei.chen@aurora.co', kind: 'Vendor', location: 'Level 4 lounge', parking: false, code: 'VF-2094', badge: '104', arrivedAt: minutesFromNow(-95) },
  { guest: 'Rami Barakat', company: 'Cobalt Systems', host: 'Nadia Salem', date: day(0), time: '10:30', purpose: 'Integration workshop', status: 'checked-in', email: 'r.barakat@cobaltsys.com', kind: 'Vendor', spaceId: 'cedar', location: where('cedar'), parking: true, code: 'VF-8812', badge: '102', arrivedAt: minutesFromNow(-240) },
  { guest: 'Ingrid Sørensen', company: 'Nordic Retail', host: 'Hana Youssef', date: day(0), time: '11:00', purpose: 'Contract walkthrough', status: 'checked-in', email: 'ingrid@nordicretail.no', kind: 'VIP', spaceId: 'lotus', location: where('lotus'), parking: true, code: 'VF-6630', badge: 'VIP-01', arrivedAt: minutesFromNow(-180) },
  { guest: 'Tom Whitfield', company: 'Greenline Facilities', host: 'Yousef Mansour', date: day(0), time: '08:30', purpose: 'HVAC inspection', status: 'checked-out', email: 't.whitfield@greenline.co.uk', kind: 'Contractor', location: 'Level 6 plant room', parking: true, code: 'VF-1187', badge: '103', arrivedAt: minutesFromNow(-560), leftAt: minutesFromNow(-320) },
  { guest: 'Yasmine Toure', company: 'Atlas Capital', host: 'Tarek Aziz', date: day(0), time: '16:30', purpose: 'Funding checkpoint', status: 'pre-registered', email: 'y.toure@atlascapital.com', kind: 'VIP', spaceId: 'boardroom', location: where('boardroom'), parking: true, code: 'VF-9041' },
  { guest: 'Daniel Okafor', company: 'Helios Group', host: 'Sara Ahmed', date: day(1), time: '11:00', purpose: 'Design portfolio review', status: 'invited', email: 'd.okafor@helios.group', kind: 'Interview', spaceId: 'studio-3', location: where('studio-3'), parking: false, code: 'VF-5516' },
  { guest: 'Claire Dubois', company: 'Lumen Studio', host: 'Rana Khalil', date: day(1), time: '14:00', purpose: 'Brand refresh pitch', status: 'pre-registered', email: 'claire@lumen.studio', kind: 'Guest', spaceId: 'studio-4', location: where('studio-4'), parking: false, code: 'VF-7208' },
  { guest: 'Abdullah Al-Harbi', company: 'Ministry of Investment', host: 'Noura Sami', date: day(1), time: '10:00', purpose: 'Delegation tour', status: 'pre-registered', email: 'a.alharbi@mise.gov.sa', kind: 'VIP', spaceId: 'boardroom', location: where('boardroom'), parking: true, code: 'VF-3355' },
  { guest: 'Priya Raman', company: 'Meridian', host: 'Sara Ahmed', date: day(-1), time: '14:00', purpose: 'Contract signing', status: 'checked-out', email: 'praman@meridian.com', kind: 'Guest', spaceId: 'orchid', location: where('orchid'), parking: true, code: 'VF-3341', arrivedAt: at('14:02', -1), leftAt: at('15:20', -1) },
  { guest: 'Marcus Reed', company: 'Vertex Labs', host: 'Hana Youssef', date: day(-1), time: '09:30', purpose: 'Technical deep dive', status: 'checked-out', email: 'm.reed@vertexlabs.io', kind: 'Guest', spaceId: 'maple', location: where('maple'), parking: false, code: 'VF-2276', arrivedAt: at('09:35', -1), leftAt: at('12:10', -1) },
  { guest: 'Sofia Marchetti', company: 'Alpine Foods', host: 'Hassan Iqbal', date: day(-1), time: '11:00', purpose: 'Catering tasting', status: 'checked-out', email: 'sofia@alpinefoods.it', kind: 'Vendor', location: 'Smart Café · Level 1', parking: false, code: 'VF-4409', arrivedAt: at('11:05', -1), leftAt: at('13:00', -1) },
  { guest: 'Jonas Weber', company: 'Helios Group', host: 'Dina Hafez', date: day(2), time: '09:30', purpose: 'Engineering interview', status: 'invited', email: 'j.weber@helios.group', kind: 'Interview', spaceId: 'olive', location: where('olive'), parking: false, code: 'VF-6127' },
  { guest: 'Nour Al-Din', company: 'Cobalt Systems', host: 'Sara Ahmed', date: day(2), time: '15:00', purpose: 'Design system audit', status: 'invited', email: 'n.aldin@cobaltsys.com', kind: 'Vendor', spaceId: 'studio-4', location: where('studio-4'), parking: false, code: 'VF-9318' },
  { guest: 'Grace Mwangi', company: 'Lumen Studio', host: 'Sara Ahmed', date: day(3), time: '11:30', purpose: 'Senior designer interview', status: 'invited', email: 'grace@lumen.studio', kind: 'Interview', spaceId: 'jasmine', location: where('jasmine'), parking: false, code: 'VF-4472' },
  { guest: 'Idris Lawal', company: 'Northwind', host: 'Sara Ahmed', date: day(-1), time: '16:00', purpose: 'Design handover', status: 'checked-out', email: 'i.lawal@northwind.com', kind: 'Guest', spaceId: 'studio-3', location: where('studio-3'), parking: false, code: 'VF-2650', arrivedAt: at('16:03', -1), leftAt: at('17:15', -1) },
  { guest: 'Aisha Bello', company: 'Northwind', host: 'Hana Youssef', date: day(2), time: '13:30', purpose: 'Renewal negotiation', status: 'invited', email: 'a.bello@northwind.com', kind: 'VIP', spaceId: 'orchid', location: where('orchid'), parking: true, code: 'VF-8874' },
  { guest: 'Victor Santos', company: 'Cobalt Systems', host: 'Ziad Morsi', date: day(3), time: '10:00', purpose: 'Architecture review', status: 'invited', email: 'v.santos@cobaltsys.com', kind: 'Vendor', spaceId: 'maple', location: where('maple'), parking: false, code: 'VF-5590' },
  { guest: 'Hala Mansour', company: 'Meridian', host: 'Laila Mostafa', date: day(3), time: '15:00', purpose: 'Compliance audit', status: 'invited', email: 'h.mansour@meridian.com', kind: 'Guest', spaceId: 'lotus', location: where('lotus'), parking: false, code: 'VF-1902' },
  { guest: 'Erik Lindqvist', company: 'Nordic Retail', host: 'Khaled Nour', date: day(4), time: '11:30', purpose: 'Expansion planning', status: 'invited', email: 'erik@nordicretail.no', kind: 'VIP', spaceId: 'boardroom', location: where('boardroom'), parking: true, code: 'VF-7745' },
];

const DESK_AND_ROOM_HOLDS: Hold[] = [
  { spaceId: 'studio-3', date: day(0), start: '10:00', end: '11:00', purpose: 'Design sync', status: 'checked-in', organizer: 'Sara Ahmed', attendees: 3, checkedInAt: at('09:58') },
  { spaceId: 'cedar', date: day(0), start: '09:00', end: '10:30', purpose: 'Sprint planning', status: 'confirmed', organizer: 'Karim Fouad', attendees: 5 },
  { spaceId: 'jasmine', date: day(0), start: '11:00', end: '12:00', purpose: 'Pair review', status: 'confirmed', organizer: 'Nadia Salem', attendees: 2 },
  { spaceId: 'jasmine', date: day(0), start: '14:30', end: '15:30', purpose: 'Roadmap triage', status: 'confirmed', organizer: 'Maya Fahmy', attendees: 4 },
  { spaceId: 'olive', date: day(0), start: '09:30', end: '10:30', purpose: 'Standup overflow', status: 'confirmed', organizer: 'Tamer Sobhy', attendees: 4 },
  { spaceId: 'olive', date: day(0), start: '13:00', end: '14:00', purpose: 'Recruiter sync', status: 'confirmed', organizer: 'Dina Hafez', attendees: 2 },
  { spaceId: 'pod-2a', date: day(0), start: '14:00', end: '15:00', purpose: 'Focus block', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 1 },
  { spaceId: 'pod-2b', date: day(0), start: '10:00', end: '12:00', purpose: 'Deep work', status: 'confirmed', organizer: 'Omar Zaki', attendees: 1 },
  { spaceId: 'desk-4-118', date: day(0), start: '09:00', end: '17:00', purpose: 'Focus day', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 1 },
  { spaceId: 'desk-4-122', date: day(0), start: '09:00', end: '17:00', purpose: 'Desk for the day', status: 'checked-in', organizer: 'Yara Sabry', attendees: 1, checkedInAt: at('08:51') },
  { spaceId: 'maple', date: day(0), start: '11:30', end: '12:30', purpose: 'Platform review', status: 'confirmed', organizer: 'Ziad Morsi', attendees: 6 },
  { spaceId: 'maple', date: day(0), start: '15:00', end: '16:00', purpose: 'Budget checkpoint', status: 'confirmed', organizer: 'Tarek Aziz', attendees: 5 },
  { spaceId: 'studio-4', date: day(0), start: '09:00', end: '10:00', purpose: 'Content planning', status: 'confirmed', organizer: 'Farah Nabil', attendees: 4 },
  { spaceId: 'studio-4', date: day(0), start: '13:30', end: '14:30', purpose: 'Campaign review', status: 'confirmed', organizer: 'Amira Shafik', attendees: 5 },
  { spaceId: 'lotus', date: day(0), start: '16:00', end: '17:00', purpose: 'Vendor demo', status: 'confirmed', organizer: 'Hana Youssef', attendees: 5 },
  { spaceId: 'orchid', date: day(0), start: '16:00', end: '17:00', purpose: 'Pipeline review', status: 'pending', organizer: 'Khaled Nour', attendees: 8 },
  { spaceId: 'boardroom', date: day(0), start: '11:00', end: '13:00', purpose: 'Board lunch', status: 'pending', organizer: 'Noura Sami', attendees: 10 },
  { spaceId: 'atrium', date: day(0), start: '09:00', end: '11:00', purpose: 'Onboarding week', status: 'pending', organizer: 'Lina Haddad', attendees: 25 },
  { spaceId: 'studio-3', date: day(0), start: '15:30', end: '16:30', purpose: 'Partnership intro', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 4 },

  { spaceId: 'studio-3', date: day(1), start: '11:00', end: '12:00', purpose: 'Portfolio review', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 3 },
  { spaceId: 'cedar', date: day(1), start: '09:30', end: '11:00', purpose: 'Retro', status: 'confirmed', organizer: 'Karim Fouad', attendees: 6 },
  { spaceId: 'desk-4-118', date: day(1), start: '09:00', end: '17:00', purpose: 'Focus day', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 1 },
  { spaceId: 'maple', date: day(1), start: '15:00', end: '16:30', purpose: 'Security review', status: 'confirmed', organizer: 'Adel Rashid', attendees: 7 },
  { spaceId: 'lab', date: day(1), start: '09:00', end: '11:00', purpose: 'Research readout', status: 'confirmed', organizer: 'Reem Othman', attendees: 12 },
  { spaceId: 'pod-2a', date: day(1), start: '13:00', end: '15:00', purpose: 'Writing block', status: 'confirmed', organizer: 'Farah Nabil', attendees: 1 },

  { spaceId: 'cedar', date: day(2), start: '10:00', end: '11:30', purpose: 'Sprint planning', status: 'confirmed', organizer: 'Karim Fouad', attendees: 5 },
  { spaceId: 'skyline', date: day(2), start: '09:00', end: '12:00', purpose: 'Leadership offsite', status: 'pending', organizer: 'Noura Sami', attendees: 18 },
  { spaceId: 'desk-4-118', date: day(2), start: '09:00', end: '17:00', purpose: 'Focus day', status: 'confirmed', organizer: 'Sara Ahmed', attendees: 1 },
  { spaceId: 'jasmine', date: day(2), start: '14:00', end: '15:00', purpose: 'One to one', status: 'confirmed', organizer: 'Lina Haddad', attendees: 2 },

  { spaceId: 'studio-3', date: day(-1), start: '10:00', end: '11:00', purpose: 'Design sync', status: 'checked-in', organizer: 'Sara Ahmed', attendees: 3, checkedInAt: at('10:01', -1) },
  { spaceId: 'cedar', date: day(-1), start: '14:00', end: '15:00', purpose: 'Incident review', status: 'checked-in', organizer: 'Sami Kamal', attendees: 6, checkedInAt: at('14:04', -1) },
  { spaceId: 'pod-2b', date: day(-1), start: '09:00', end: '11:00', purpose: 'Deep work', status: 'checked-in', organizer: 'Omar Zaki', attendees: 1, checkedInAt: at('09:00', -1) },
];

const eventHolds: Hold[] = EVENTS.filter((event) => event.spaceId && event.status === 'published').map(
  (event) => ({
    spaceId: event.spaceId,
    date: event.date,
    start: event.start,
    end: event.end,
    purpose: event.title,
    status: 'confirmed' as const,
    organizer: event.host,
    attendees: event.going.length,
    eventId: event.id,
  }),
);

const visitHolds: Hold[] = VISITS.filter((visit) => visit.spaceId && visit.status !== 'cancelled').map(
  (visit) => ({
    spaceId: visit.spaceId,
    date: visit.date,
    start: visit.time,
    end: `${String(Number(visit.time.slice(0, 2)) + 1).padStart(2, '0')}${visit.time.slice(2)}`,
    purpose: `${visit.purpose} — ${visit.company}`,
    status: 'confirmed' as const,
    organizer: visit.host,
    attendees: 4,
  }),
);

export const BOOKINGS: New<Booking>[] = [
  ...DESK_AND_ROOM_HOLDS,
  ...eventHolds,
  ...visitHolds,
].map((hold) => {
  const space = spaceById.get(hold.spaceId ?? '');
  return {
    ...hold,
    space: space?.name ?? 'Riyadh HQ',
    level: space?.level ?? 'Level 1',
    capacity: space?.capacity ?? 8,
  };
});

export const MEETINGS: New<Meeting>[] = [
  { title: 'Design sync', space: 'Studio 3', level: 'Level 2', start: minutesFromNow(25), end: minutesFromNow(85), attendees: ['SA', 'RK', 'RO'], status: 'confirmed' },
  { title: 'Lunch & Learn: Design Systems', space: 'Innovation Lab', level: 'Level 3', start: minutesFromNow(85), end: minutesFromNow(145), attendees: ['SA', 'RK', 'YS', 'MF'], status: 'confirmed' },
  { title: 'Client visit — Northwind', space: 'Orchid', level: 'Level 5', start: minutesFromNow(150), end: minutesFromNow(210), attendees: ['SA', 'HY'], status: 'confirmed' },
  { title: 'Partnership intro — Vertex Labs', space: 'Studio 3', level: 'Level 2', start: minutesFromNow(215), end: minutesFromNow(275), attendees: ['SA', 'HY'], status: 'confirmed' },
  { title: 'A little focus time', space: 'Pod 2-A', level: 'Level 2', start: minutesFromNow(280), end: minutesFromNow(340), attendees: ['SA'], status: 'tentative' },
];

export const BADGES: New<Badge>[] = [
  { number: '101' },
  { number: '102', visitId: 'seed_3' },
  { number: '103' },
  { number: '104', visitId: 'seed_2' },
  { number: '105' },
  { number: '106' },
  { number: '107' },
  { number: '108' },
  { number: '109' },
  { number: '110' },
  { number: 'VIP-01', visitId: 'seed_4' },
  { number: 'VIP-02' },
];

export const DELIVERIES: New<Delivery>[] = [
  { recipient: 'Sara Ahmed', carrier: 'DHL', tracking: '7850 0212 3456', collected: false },
  { recipient: 'Karim Fouad', carrier: 'Aramex', tracking: '4471 9930 1122', collected: false },
  { recipient: 'Rana Khalil', carrier: 'SMSA', tracking: '2039 8871 4520', collected: false },
  { recipient: 'Ziad Morsi', carrier: 'DHL', tracking: '6612 3390 8874', collected: false },
  { recipient: 'Salma Gaber', carrier: 'Aramex', tracking: '1180 5567 2341', collected: false },
  { recipient: 'Nadia Salem', carrier: 'FedEx', tracking: '9920 4417 8830', collected: true },
  { recipient: 'Hassan Iqbal', carrier: 'Alpine Foods', tracking: 'AF-2291', collected: true },
  { recipient: 'Bassem Riad', carrier: 'SMSA', tracking: '7741 2098 6633', collected: true },
];

export const ORDERS: New<Order>[] = [
  {
    item: 'Flat White',
    options: 'Large · Oat · Extra shot',
    destination: 'Studio 3 · Level 2',
    price: 23,
    status: 'on-the-way',
    lines: [{ menuItemId: 'flat-white', name: 'Flat White', options: 'Large · Oat · Extra shot', unitPrice: 23, quantity: 1 }],
  },
  {
    item: 'Karak Tea',
    options: 'Regular · Extra cardamom',
    destination: 'Cedar · Level 3',
    price: 36,
    status: 'preparing',
    lines: [{ menuItemId: 'karak-tea', name: 'Karak Tea', options: 'Regular · Extra cardamom', unitPrice: 12, quantity: 3 }],
  },
  {
    item: 'Mezze Platter',
    options: 'For four',
    destination: 'Orchid · Level 5',
    price: 140,
    status: 'placed',
    note: 'Client lunch — please plate it properly.',
    lines: [{ menuItemId: 'mezze-platter', name: 'Mezze Platter', options: 'For four', unitPrice: 140, quantity: 1 }],
  },
  {
    item: 'Cortado',
    options: 'Regular',
    destination: 'Desk 4-122',
    price: 18,
    status: 'on-the-way',
    lines: [{ menuItemId: 'cortado', name: 'Cortado', options: 'Regular', unitPrice: 18, quantity: 1 }],
  },
  {
    item: 'Jasmine Green Tea',
    options: 'Regular',
    destination: 'Desk 4-118',
    price: 21,
    status: 'delivered',
    lines: [
      { menuItemId: 'green-tea', name: 'Jasmine Green Tea', options: 'Regular', unitPrice: 9, quantity: 1 },
      { menuItemId: 'blueberry-muffin', name: 'Blueberry Muffin', options: 'Warmed', unitPrice: 12, quantity: 1 },
    ],
  },
  {
    item: 'Iced Latte',
    options: 'Large · Almond',
    destination: 'Innovation Lab · Level 3',
    price: 50,
    status: 'delivered',
    lines: [{ menuItemId: 'iced-latte', name: 'Iced Latte', options: 'Large · Almond', unitPrice: 25, quantity: 2 }],
  },
  {
    item: 'Chicken Shawarma Bowl',
    options: 'Spicy · No pickles',
    destination: 'Desk 4-118',
    price: 45,
    status: 'delivered',
    lines: [{ menuItemId: 'shawarma-bowl', name: 'Chicken Shawarma Bowl', options: 'Spicy · No pickles', unitPrice: 45, quantity: 1 }],
  },
  {
    item: 'Date Smoothie',
    options: 'Regular',
    destination: 'Roof Garden · Level 7',
    price: 28,
    status: 'delivered',
    lines: [{ menuItemId: 'date-smoothie', name: 'Date Smoothie', options: 'Regular', unitPrice: 28, quantity: 1 }],
  },
];

export const TICKETS: New<Ticket>[] = [
  { subject: 'Projector not connecting in Orchid', category: 'AV', location: 'Level 5 · Orchid', priority: 'high', status: 'in-progress' },
  { subject: 'Level 4 north wing feels warm', category: 'Comfort', location: 'Level 4', priority: 'medium', status: 'open' },
  { subject: 'Badge reader rejecting on Level 6', category: 'Access', location: 'Level 6 · Lift lobby', priority: 'high', status: 'in-progress' },
  { subject: 'Coffee machine leaking in the café', category: 'Catering', location: 'Level 1 · Smart Café', priority: 'medium', status: 'open' },
  { subject: 'Standing desk motor jammed', category: 'Furniture', location: 'Level 4 · Desk 4-120', priority: 'low', status: 'in-progress' },
  { subject: 'Wi-Fi drops in the Roof Garden', category: 'Network', location: 'Level 7', priority: 'medium', status: 'open' },
  { subject: 'Whiteboard markers all dry in Cedar', category: 'Supplies', location: 'Level 3 · Cedar', priority: 'low', status: 'open' },
  { subject: 'Forum microphone feedback', category: 'AV', location: 'Level 1 · The Forum', priority: 'high', status: 'resolved' },
  { subject: 'Parking barrier slow to lift', category: 'Access', location: 'Basement 1', priority: 'low', status: 'resolved' },
  { subject: 'Recycling bins not collected', category: 'Cleaning', location: 'Level 2', priority: 'low', status: 'resolved' },
];

export const TASKS: New<Task>[] = [
  { title: 'Approve Northwind visit agenda', due: 'Today · 12:00', effort: 'quick', done: false },
  { title: 'Review Q3 space utilisation', due: 'Today · 16:00', effort: 'focused', done: false },
  { title: 'Confirm Lunch & Learn catering headcount', due: 'Today · 11:00', effort: 'quick', done: false },
  { title: 'Draft the design system talk outline', due: 'Today · 12:00', effort: 'deep', done: false },
  { title: 'Send Daniel the interview brief', due: 'Tomorrow · 09:00', effort: 'quick', done: false },
  { title: 'Pick the Tech Summit breakout tracks', due: 'Tomorrow · 15:00', effort: 'focused', done: false },
  { title: 'Reply to Vertex Labs on the pilot scope', due: 'Tomorrow', effort: 'focused', done: false },
  { title: 'Sign off signage refresh', due: 'Yesterday', effort: 'quick', done: true },
  { title: 'Book the Q4 offsite space', due: 'Yesterday', effort: 'quick', done: true },
  { title: 'Close out the hack day retro notes', due: 'Yesterday', effort: 'focused', done: true },
];

export const NOTIFICATIONS: New<Notification>[] = [
  { title: 'Layla Nasser pre-registered', body: 'Arriving 13:00 · Orchid, Level 5', product: 'VisitFlow', read: false },
  { title: 'Lunch & Learn starts in an hour', body: 'Innovation Lab · 14 going, 2 waiting', product: 'Gather', read: false },
  { title: 'Studio 3 is ready', body: 'Comfort set for your 10:00 sync', product: 'Atmosphere', read: false },
  { title: 'Two people joined your waitlist', body: 'Design Systems at Scale is now full', product: 'Gather', read: false },
  { title: 'Ingrid Sørensen has checked in', body: 'VIP · Lotus, Level 5 · badge VIP-01', product: 'VisitFlow', read: false },
  { title: 'Your flat white is on the way', body: 'Delivering to Studio 3', product: 'Nourish', read: true },
  { title: 'Orchid needs your approval', body: 'Khaled Nour requested 16:00–17:00', product: 'SpaceOS', read: true },
  { title: 'Q4 All-Hands is tomorrow', body: 'The Forum · 14:00 · attendance expected', product: 'Gather', read: true },
  { title: 'Projector ticket picked up', body: 'AV team is on Level 5 now', product: 'Resolve', read: true },
  { title: 'Desk 4-120 is offline', body: 'Monitor arm replacement — back Thursday', product: 'SpaceOS', read: true },
  { title: 'Nadia Salem posted in Tech Talks', body: 'The agents deep dive deck is up', product: 'Tribes', read: false },
  { title: 'Two people want to join Giving Back', body: 'Tarek Aziz and Yara Sabry are waiting', product: 'Tribes', read: false },
];

export const TRIBES: Array<New<Tribe> & { id: string }> = [
  {
    id: 'tr-tech-talks',
    name: 'Tech Talks',
    category: 'Professional',
    tagline: 'Weekly deep dives into whatever we just shipped.',
    about:
      'Engineers, data folk and the curious. Every Wednesday someone walks the room through something they built, broke or read. No slides required, working code preferred.',
    lead: 'Nadia Salem',
    access: 'open',
    archived: false,
    home: where('lab'),
    tags: ['Engineering', 'Learning', 'Weekly'],
    members: ['Nadia Salem', 'Karim Fouad', 'Ziad Morsi', 'Sami Kamal', 'Yara Sabry', 'Tamer Sobhy', 'Omar Zaki', 'Maya Fahmy', 'Bassem Riad', 'Sara Ahmed', 'Rana Khalil', 'Fadi Barakat', 'Amira Shafik', 'Khaled Nour', 'Noura Sami', 'Reem Othman', 'Dina Hafez', 'Farah Nabil', 'Hana Youssef'],
    pending: [],
  },
  {
    id: 'tr-design-guild',
    name: 'Design Guild',
    category: 'Professional',
    tagline: 'Critique, craft, and keeping the system honest.',
    about:
      'A standing crit for anyone who ships an interface. Bring work at any fidelity — the rule is you leave with one decision made, not a list of opinions.',
    lead: 'Sara Ahmed',
    access: 'open',
    archived: false,
    home: where('studio-3'),
    tags: ['Design', 'Critique'],
    members: ['Sara Ahmed', 'Rana Khalil', 'Reem Othman', 'Maya Fahmy', 'Farah Nabil', 'Amira Shafik', 'Yara Sabry', 'Salma Gaber', 'Nadia Salem'],
    pending: [],
  },
  {
    id: 'tr-run-club',
    name: 'Run Club',
    category: 'Wellness',
    tagline: 'Out the north lobby at 06:30, back before stand-up.',
    about:
      'Five and ten kilometre loops along the wadi path, three mornings a week. Every pace is covered and nobody gets left behind — the slow group is the big group.',
    lead: 'Tamer Sobhy',
    access: 'open',
    archived: false,
    home: 'North lobby · Level 1',
    tags: ['Running', 'Mornings'],
    members: ['Tamer Sobhy', 'Mona Darwish', 'Sara Ahmed', 'Sami Kamal', 'Adel Rashid', 'Yara Sabry', 'Omar Zaki', 'Waleed Tantawy', 'Fadi Barakat', 'Khaled Nour', 'Dina Hafez', 'Ziad Morsi'],
    pending: [],
  },
  {
    id: 'tr-mindful',
    name: 'Mindful Mornings',
    category: 'Wellness',
    tagline: 'Forty minutes on the roof before the inbox opens.',
    about:
      'Guided breathing and a slow flow on the Roof Garden, twice a week. Mats are in the cupboard by the lift. Come as you are, leave before anyone notices you were gone.',
    lead: 'Mona Darwish',
    access: 'open',
    archived: false,
    home: where('roof-garden'),
    tags: ['Yoga', 'Calm'],
    members: ['Mona Darwish', 'Lina Haddad', 'Dina Hafez', 'Laila Mostafa', 'Reem Othman', 'Amira Shafik', 'Noura Sami', 'Hana Youssef'],
    pending: [],
  },
  {
    id: 'tr-coffee',
    name: 'Coffee Aficionados',
    category: 'Social',
    tagline: 'Chasing the perfect cup, one origin at a time.',
    about:
      'We taste what the café is roasting, argue about grind size, and occasionally learn to pour a rosetta. Hassan opens the bar early for us on tasting days.',
    lead: 'Hassan Iqbal',
    access: 'open',
    archived: false,
    home: 'Nourish café · Level 1',
    tags: ['Coffee', 'Tasting'],
    members: ['Hassan Iqbal', 'Sara Ahmed', 'Tarek Aziz', 'Bassem Riad', 'Rana Khalil', 'Farah Nabil', 'Salma Gaber', 'Maya Fahmy', 'Yousef Mansour', 'Karim Fouad', 'Laila Mostafa', 'Waleed Tantawy', 'Amira Shafik', 'Fadi Barakat', 'Yara Sabry'],
    pending: [],
  },
  {
    id: 'tr-board-games',
    name: 'Board Game Night',
    category: 'Social',
    tagline: 'Last Thursday of the month, and it runs late.',
    about:
      'Heavy euros on one table, party games on the other, and a shelf in the Skyline Lounge that keeps growing. Teaching games is the whole point — turn up knowing nothing.',
    lead: 'Bassem Riad',
    access: 'open',
    archived: false,
    home: where('skyline'),
    tags: ['Games', 'Evening'],
    members: ['Bassem Riad', 'Salma Gaber', 'Tamer Sobhy', 'Sami Kamal', 'Omar Zaki', 'Ziad Morsi', 'Maya Fahmy', 'Tarek Aziz', 'Yara Sabry', 'Reem Othman', 'Dina Hafez'],
    pending: [],
  },
  {
    id: 'tr-book-club',
    name: 'Book Club',
    category: 'Creative',
    tagline: 'One book a month, and we actually finish it.',
    about:
      'Fiction one month, something argumentative the next. We keep the group small on purpose so everyone gets to speak — that is why joining needs a nod from Farah.',
    lead: 'Farah Nabil',
    access: 'request',
    archived: false,
    home: where('jasmine'),
    tags: ['Reading', 'Monthly'],
    members: ['Farah Nabil', 'Laila Mostafa', 'Noura Sami', 'Reem Othman', 'Lina Haddad', 'Amira Shafik', 'Hana Youssef'],
    pending: ['Sara Ahmed', 'Omar Zaki'],
  },
  {
    id: 'tr-photo',
    name: 'Shutter Club',
    category: 'Creative',
    tagline: 'A monthly theme, and whatever camera you own.',
    about:
      'Phone photographers and lens hoarders in the same room. We set a theme, shoot for four weeks, then print the best dozen and hang them in the Atrium.',
    lead: 'Rana Khalil',
    access: 'open',
    archived: false,
    home: where('atrium'),
    tags: ['Photography', 'Print'],
    members: ['Rana Khalil', 'Sara Ahmed', 'Reem Othman', 'Salma Gaber', 'Yara Sabry', 'Adel Rashid', 'Omar Zaki', 'Maya Fahmy', 'Tarek Aziz', 'Farah Nabil'],
    pending: [],
  },
  {
    id: 'tr-giving',
    name: 'Giving Back',
    category: 'Giving',
    tagline: 'Volunteering days, drives, and the annual build.',
    about:
      'We run the school refurbishment weekend, the winter coat drive and the blood donation days. Everything is organised through People, so joining goes past Lina first.',
    lead: 'Lina Haddad',
    access: 'request',
    archived: false,
    home: where('forum'),
    tags: ['Volunteering', 'Community'],
    members: ['Lina Haddad', 'Mona Darwish', 'Dina Hafez', 'Noura Sami', 'Laila Mostafa', 'Hana Youssef', 'Khaled Nour', 'Amira Shafik', 'Adel Rashid', 'Yousef Mansour', 'Waleed Tantawy', 'Salma Gaber', 'Farah Nabil'],
    pending: ['Tarek Aziz', 'Yara Sabry', 'Sami Kamal'],
  },
  {
    id: 'tr-new-joiners',
    name: 'New Joiners',
    category: 'Social',
    tagline: 'Your first ninety days, with company.',
    about:
      'Everyone who started in the last two quarters, plus a rotating cast of people who remember what it was like. Lunches, building tours, and the questions nobody wants to ask in a channel.',
    lead: 'Dina Hafez',
    access: 'open',
    archived: false,
    home: where('skyline'),
    tags: ['Onboarding', 'Lunch'],
    members: ['Dina Hafez', 'Lina Haddad', 'Yara Sabry', 'Sami Kamal', 'Maya Fahmy', 'Waleed Tantawy'],
    pending: [],
  },
  {
    id: 'tr-cycling',
    name: 'Weekend Cycling',
    category: 'Wellness',
    tagline: 'Paused while the ring road works are on.',
    about:
      'Saturday morning road rides out past the diplomatic quarter. On hold until the cycle lane reopens — the route is not safe with the diversion in place.',
    lead: 'Khaled Nour',
    access: 'open',
    archived: true,
    home: 'Basement 1 · bike store',
    tags: ['Cycling', 'Weekends'],
    members: ['Khaled Nour', 'Fadi Barakat', 'Sami Kamal', 'Waleed Tantawy'],
    pending: [],
  },
];

export const POSTS: Array<New<Post> & { id: string }> = [
  {
    id: 'po-tech-pinned',
    tribeId: 'tr-tech-talks',
    author: 'Nadia Salem',
    body: 'Standing invitation: the Wednesday slot is yours if you want it. Fifteen minutes, no deck needed, and half-finished counts. Drop a reply here and I will put you on the board.',
    at: hoursAgo(190),
    kind: 'update',
    pinned: true,
    likes: ['Karim Fouad', 'Ziad Morsi', 'Yara Sabry', 'Sami Kamal', 'Maya Fahmy', 'Omar Zaki', 'Sara Ahmed'],
    replies: [
      { author: 'Yara Sabry', body: 'Put me down for the render pipeline rewrite. It is ugly but it is fast.', at: hoursAgo(186) },
      { author: 'Nadia Salem', body: 'Booked you for the 14th. Ugly and fast is exactly the talk I want.', at: hoursAgo(184) },
    ],
  },
  {
    id: 'po-tech-agents',
    tribeId: 'tr-tech-talks',
    author: 'Ziad Morsi',
    body: 'Slides from this morning on running agents in production are up in Vault. The short version: the retry budget matters more than the model, and every tool call needs a timeout you actually tested.',
    at: hoursAgo(3),
    kind: 'update',
    pinned: false,
    likes: ['Nadia Salem', 'Karim Fouad', 'Sami Kamal', 'Omar Zaki', 'Tamer Sobhy', 'Maya Fahmy', 'Bassem Riad', 'Yara Sabry'],
    replies: [
      { author: 'Omar Zaki', body: 'The cost-per-resolved-ticket chart is the one I am stealing for the Data review.', at: hoursAgo(2) },
      { author: 'Karim Fouad', body: 'Take it. That chart is why we got the budget.', at: hoursAgo(1) },
    ],
  },
  {
    id: 'po-tech-hackday',
    tribeId: 'tr-tech-talks',
    author: 'Karim Fouad',
    body: 'Hack day teams are forming in the Innovation Lab. Four people still without a table, and two ideas that badly need a front-end. Come and be adopted.',
    at: hoursAgo(28),
    kind: 'update',
    pinned: false,
    likes: ['Yara Sabry', 'Sami Kamal', 'Tamer Sobhy', 'Ziad Morsi', 'Rana Khalil'],
    replies: [{ author: 'Yara Sabry', body: 'On my way up. Tell them the front-end has arrived.', at: hoursAgo(27) }],
  },
  {
    id: 'po-tech-question',
    tribeId: 'tr-tech-talks',
    author: 'Bassem Riad',
    body: 'Has anyone got the meeting room displays talking to the booking API without the vendor SDK? The SDK pulls in half of Electron and the panels have 2 GB of RAM.',
    at: hoursAgo(52),
    kind: 'question',
    pinned: false,
    likes: ['Sami Kamal', 'Ziad Morsi'],
    replies: [
      { author: 'Sami Kamal', body: 'Yes — plain fetch against the REST endpoint, poll every 30s. I will send you the systemd unit.', at: hoursAgo(50) },
      { author: 'Bassem Riad', body: 'That is 400 MB saved per panel. Thank you.', at: hoursAgo(49) },
    ],
  },
  {
    id: 'po-tech-win',
    tribeId: 'tr-tech-talks',
    author: 'Sami Kamal',
    body: 'Build times went from eleven minutes to ninety seconds. Turns out we were rebuilding the design tokens on every single package. One cache key.',
    at: hoursAgo(74),
    kind: 'win',
    pinned: false,
    likes: ['Nadia Salem', 'Karim Fouad', 'Yara Sabry', 'Tamer Sobhy', 'Ziad Morsi', 'Maya Fahmy', 'Sara Ahmed', 'Reem Othman', 'Bassem Riad'],
    replies: [{ author: 'Tamer Sobhy', body: 'Ninety seconds. I can finally run the suite before lunch instead of after it.', at: hoursAgo(72) }],
  },
  {
    id: 'po-design-pinned',
    tribeId: 'tr-design-guild',
    author: 'Sara Ahmed',
    body: 'House rule, pinned so nobody has to ask: bring work at any fidelity, but bring a question with it. "What do you think?" gets you opinions. "Should this be a sheet or a page?" gets you a decision.',
    at: hoursAgo(220),
    kind: 'update',
    pinned: true,
    likes: ['Rana Khalil', 'Reem Othman', 'Maya Fahmy', 'Amira Shafik', 'Yara Sabry', 'Salma Gaber'],
    replies: [],
  },
  {
    id: 'po-design-crit',
    tribeId: 'tr-design-guild',
    author: 'Reem Othman',
    body: 'Crit notes from Studio 3 are written up. The booking flow loses people at the room picker, not the calendar — four of six testers scrolled past the level filter without seeing it.',
    at: hoursAgo(9),
    kind: 'update',
    pinned: false,
    likes: ['Sara Ahmed', 'Rana Khalil', 'Maya Fahmy', 'Nadia Salem', 'Yara Sabry'],
    replies: [
      { author: 'Sara Ahmed', body: 'That matches the heatmap. Let us try the filter as chips above the grid rather than a select.', at: hoursAgo(8) },
      { author: 'Maya Fahmy', body: 'I will get it into the next sprint. Chips are cheap.', at: hoursAgo(6) },
    ],
  },
  {
    id: 'po-design-tokens',
    tribeId: 'tr-design-guild',
    author: 'Rana Khalil',
    body: 'The purple is now one hue across every surface — no more three-greys-that-are-almost-the-same. Anything still hardcoded is a bug, send it to me and I will fix it at the token.',
    at: hoursAgo(44),
    kind: 'win',
    pinned: false,
    likes: ['Sara Ahmed', 'Reem Othman', 'Amira Shafik', 'Farah Nabil', 'Yara Sabry', 'Salma Gaber', 'Maya Fahmy'],
    replies: [{ author: 'Amira Shafik', body: 'The decks look like one company for the first time. Thank you.', at: hoursAgo(41) }],
  },
  {
    id: 'po-design-question',
    tribeId: 'tr-design-guild',
    author: 'Yara Sabry',
    body: 'Empty states — illustration or plain sentence? We have both in the product right now and it reads like two different apps.',
    at: hoursAgo(97),
    kind: 'question',
    pinned: false,
    likes: ['Reem Othman', 'Maya Fahmy'],
    replies: [
      { author: 'Sara Ahmed', body: 'Sentence plus the one action that fixes it. Illustrations age badly and nobody reads them twice.', at: hoursAgo(95) },
      { author: 'Rana Khalil', body: 'Agreed. Save the drawing budget for onboarding.', at: hoursAgo(94) },
    ],
  },
  {
    id: 'po-run-pinned',
    tribeId: 'tr-run-club',
    author: 'Tamer Sobhy',
    body: 'Routes and paces live here. Sunday and Tuesday are the five kilometre loop, Thursday is ten. We leave the north lobby at 06:30 sharp and the back group never runs alone.',
    at: hoursAgo(300),
    kind: 'update',
    pinned: true,
    likes: ['Mona Darwish', 'Sami Kamal', 'Adel Rashid', 'Yara Sabry', 'Omar Zaki', 'Sara Ahmed'],
    replies: [],
  },
  {
    id: 'po-run-weather',
    tribeId: 'tr-run-club',
    author: 'Mona Darwish',
    body: 'Thirty-one degrees by seven tomorrow, so we are moving the ten kilometre to 06:00 and cutting it to eight. Bring more water than you think you need.',
    at: hoursAgo(5),
    kind: 'update',
    pinned: false,
    likes: ['Tamer Sobhy', 'Sami Kamal', 'Adel Rashid', 'Waleed Tantawy', 'Fadi Barakat', 'Ziad Morsi'],
    replies: [
      { author: 'Sami Kamal', body: 'Six it is. Anyone want a lift from the north gate?', at: hoursAgo(4) },
      { author: 'Dina Hafez', body: 'Yes please — I am always the one sprinting across the car park.', at: hoursAgo(3) },
    ],
  },
  {
    id: 'po-run-pb',
    tribeId: 'tr-run-club',
    author: 'Yara Sabry',
    body: 'Went under twenty-five minutes on the five for the first time. Six months ago I could not finish it without walking the hill.',
    at: hoursAgo(31),
    kind: 'win',
    pinned: false,
    likes: ['Tamer Sobhy', 'Mona Darwish', 'Sami Kamal', 'Omar Zaki', 'Adel Rashid', 'Khaled Nour', 'Dina Hafez', 'Ziad Morsi', 'Sara Ahmed'],
    replies: [
      { author: 'Tamer Sobhy', body: 'That hill has beaten better runners than both of us. Well done.', at: hoursAgo(30) },
      { author: 'Mona Darwish', body: 'Next stop, the ten. You are ready whether you believe it or not.', at: hoursAgo(29) },
    ],
  },
  {
    id: 'po-run-shoes',
    tribeId: 'tr-run-club',
    author: 'Omar Zaki',
    body: 'Anyone know a shop in Riyadh that does proper gait analysis? My knees have opinions about the last pair I bought online.',
    at: hoursAgo(120),
    kind: 'question',
    pinned: false,
    likes: ['Fadi Barakat', 'Waleed Tantawy'],
    replies: [{ author: 'Adel Rashid', body: 'The place on Tahlia does it free if you buy there. Ask for Faisal.', at: hoursAgo(118) }],
  },
  {
    id: 'po-mindful-pinned',
    tribeId: 'tr-mindful',
    author: 'Mona Darwish',
    body: 'Mats, blocks and straps are in the cupboard by the Roof Garden lift. Take one, leave one. No experience needed and nobody is looking at you.',
    at: hoursAgo(260),
    kind: 'update',
    pinned: true,
    likes: ['Lina Haddad', 'Dina Hafez', 'Laila Mostafa', 'Reem Othman', 'Noura Sami'],
    replies: [],
  },
  {
    id: 'po-mindful-week',
    tribeId: 'tr-mindful',
    author: 'Mona Darwish',
    body: 'Wellness Week opens on the roof with a long slow flow and breakfast after. It is a draft in Gather while I confirm the caterer — I will publish it the moment Nourish come back to me.',
    at: hoursAgo(20),
    kind: 'update',
    pinned: false,
    likes: ['Lina Haddad', 'Amira Shafik', 'Noura Sami', 'Hana Youssef', 'Dina Hafez'],
    replies: [{ author: 'Lina Haddad', body: 'People will cover the breakfast. Book for forty and send me the invoice.', at: hoursAgo(19) }],
  },
  {
    id: 'po-mindful-quiet',
    tribeId: 'tr-mindful',
    author: 'Laila Mostafa',
    body: 'Twenty minutes on the roof before my first call has done more for my week than any productivity system I have tried. That is the whole review.',
    at: hoursAgo(66),
    kind: 'win',
    pinned: false,
    likes: ['Mona Darwish', 'Lina Haddad', 'Reem Othman', 'Noura Sami', 'Amira Shafik', 'Hana Youssef'],
    replies: [],
  },
  {
    id: 'po-coffee-pinned',
    tribeId: 'tr-coffee',
    author: 'Hassan Iqbal',
    body: 'The bar opens at 07:30 on tasting days, half an hour before the café proper. Come up the back stairs and knock — the shutter looks closed but it is not.',
    at: hoursAgo(240),
    kind: 'update',
    pinned: true,
    likes: ['Sara Ahmed', 'Tarek Aziz', 'Bassem Riad', 'Rana Khalil', 'Farah Nabil', 'Maya Fahmy'],
    replies: [],
  },
  {
    id: 'po-coffee-origin',
    tribeId: 'tr-coffee',
    author: 'Hassan Iqbal',
    body: 'New single origin landed this morning — a washed Yirgacheffe that tastes like lemon and honey and nothing like the last one. Bringing it to the tasting so nobody has to take my word for it.',
    at: hoursAgo(11),
    kind: 'update',
    pinned: false,
    likes: ['Sara Ahmed', 'Tarek Aziz', 'Rana Khalil', 'Salma Gaber', 'Karim Fouad', 'Laila Mostafa', 'Yara Sabry', 'Fadi Barakat'],
    replies: [
      { author: 'Tarek Aziz', body: 'Lemon and honey is a big claim. I will be the sceptic at the end of the bar.', at: hoursAgo(10) },
      { author: 'Hassan Iqbal', body: 'Every group needs one. Your cup is already poured.', at: hoursAgo(9) },
    ],
  },
  {
    id: 'po-coffee-grinder',
    tribeId: 'tr-coffee',
    author: 'Maya Fahmy',
    body: 'Is the Level 4 grinder meant to sound like that? It has developed a rattle and the grind is all over the place.',
    at: hoursAgo(38),
    kind: 'question',
    pinned: false,
    likes: ['Bassem Riad'],
    replies: [
      { author: 'Hassan Iqbal', body: 'No. Burr is loose — I have raised it with Resolve, do not use it until they have been.', at: hoursAgo(37) },
      { author: 'Yousef Mansour', body: 'Ticket is open and the part is in the building. Tomorrow morning.', at: hoursAgo(35) },
    ],
  },
  {
    id: 'po-coffee-latte',
    tribeId: 'tr-coffee',
    author: 'Rana Khalil',
    body: 'Poured my first rosetta that actually looked like a leaf. Twenty-two attempts. I am told this is normal and I choose to believe it.',
    at: hoursAgo(90),
    kind: 'win',
    pinned: false,
    likes: ['Hassan Iqbal', 'Sara Ahmed', 'Salma Gaber', 'Farah Nabil', 'Amira Shafik', 'Bassem Riad', 'Laila Mostafa'],
    replies: [{ author: 'Hassan Iqbal', body: 'Twenty-two is quick. Mine took most of a winter.', at: hoursAgo(88) }],
  },
  {
    id: 'po-games-night',
    tribeId: 'tr-board-games',
    author: 'Bassem Riad',
    body: 'Skyline Lounge is booked for Thursday from six. Heavy table is doing Brass, party table is whatever Salma pulls off the shelf. Food is ordered through Nourish at seven.',
    at: hoursAgo(7),
    kind: 'update',
    pinned: true,
    likes: ['Salma Gaber', 'Tamer Sobhy', 'Sami Kamal', 'Omar Zaki', 'Ziad Morsi', 'Maya Fahmy', 'Tarek Aziz'],
    replies: [
      { author: 'Salma Gaber', body: 'Bringing the one with the tiny wooden chickens. No further details.', at: hoursAgo(6) },
      { author: 'Omar Zaki', body: 'Tiny wooden chickens has never once been a bad sign.', at: hoursAgo(5) },
    ],
  },
  {
    id: 'po-games-shelf',
    tribeId: 'tr-board-games',
    author: 'Salma Gaber',
    body: 'The shelf is now thirty-one boxes deep and two of them have never been opened. If you have been meaning to learn something heavy, Thursday is the night — I will teach anything up there.',
    at: hoursAgo(58),
    kind: 'update',
    pinned: false,
    likes: ['Bassem Riad', 'Reem Othman', 'Dina Hafez', 'Yara Sabry', 'Maya Fahmy'],
    replies: [],
  },
  {
    id: 'po-book-current',
    tribeId: 'tr-book-club',
    author: 'Farah Nabil',
    body: 'This month is Piranesi. Meeting in Jasmine, and the only preparation required is having finished it — no notes, no summaries, just turn up with the bit that stayed with you.',
    at: hoursAgo(15),
    kind: 'update',
    pinned: true,
    likes: ['Laila Mostafa', 'Noura Sami', 'Reem Othman', 'Lina Haddad', 'Amira Shafik'],
    replies: [
      { author: 'Noura Sami', body: 'Finished it on the flight back and immediately started it again.', at: hoursAgo(13) },
      { author: 'Reem Othman', body: 'Two chapters left and I am rationing them.', at: hoursAgo(12) },
    ],
  },
  {
    id: 'po-book-next',
    tribeId: 'tr-book-club',
    author: 'Laila Mostafa',
    body: 'Nominations for next month, one each please. I will put the top three to a vote on Thursday so we are not still arguing about it in Jasmine.',
    at: hoursAgo(64),
    kind: 'question',
    pinned: false,
    likes: ['Farah Nabil', 'Amira Shafik', 'Hana Youssef'],
    replies: [{ author: 'Hana Youssef', body: 'The Wager. It reads like a thriller and it is all true.', at: hoursAgo(61) }],
  },
  {
    id: 'po-photo-theme',
    tribeId: 'tr-photo',
    author: 'Rana Khalil',
    body: 'This month the theme is Lines. Stairwells, shadows, the car park at six — anything where the geometry is the subject. Twelve get printed and hung in the Atrium on the last Sunday.',
    at: hoursAgo(26),
    kind: 'update',
    pinned: true,
    likes: ['Sara Ahmed', 'Reem Othman', 'Salma Gaber', 'Yara Sabry', 'Adel Rashid', 'Omar Zaki', 'Tarek Aziz'],
    replies: [
      { author: 'Adel Rashid', body: 'The service stair on Level 6 at about half four is unreal. You are welcome.', at: hoursAgo(24) },
      { author: 'Sara Ahmed', body: 'Going up there tomorrow before it gets out.', at: hoursAgo(22) },
    ],
  },
  {
    id: 'po-photo-print',
    tribeId: 'tr-photo',
    author: 'Salma Gaber',
    body: 'Last month’s prints are up by the Atrium stairs. Seeing your own photo at A2 on a wall is a completely different feeling to seeing it on a phone — worth entering just for that.',
    at: hoursAgo(82),
    kind: 'win',
    pinned: false,
    likes: ['Rana Khalil', 'Sara Ahmed', 'Reem Othman', 'Maya Fahmy', 'Farah Nabil', 'Yara Sabry'],
    replies: [],
  },
  {
    id: 'po-giving-build',
    tribeId: 'tr-giving',
    author: 'Lina Haddad',
    body: 'The school refurbishment weekend is confirmed for next month — painting, shelving and a library that needs rebuilding from the floor up. Twenty-two places, and every one of them fills.',
    at: hoursAgo(18),
    kind: 'update',
    pinned: true,
    likes: ['Mona Darwish', 'Dina Hafez', 'Noura Sami', 'Laila Mostafa', 'Khaled Nour', 'Amira Shafik', 'Adel Rashid', 'Waleed Tantawy'],
    replies: [
      { author: 'Yousef Mansour', body: 'I can get the paint at trade price and a van for the Saturday.', at: hoursAgo(16) },
      { author: 'Lina Haddad', body: 'That is half the budget solved before we have started. Thank you.', at: hoursAgo(15) },
    ],
  },
  {
    id: 'po-giving-coats',
    tribeId: 'tr-giving',
    author: 'Dina Hafez',
    body: 'Winter coat drive closed at four hundred and sixty coats, up from two hundred and ten last year. The collection point by reception stays open for anything that arrives late.',
    at: hoursAgo(108),
    kind: 'win',
    pinned: false,
    likes: ['Lina Haddad', 'Mona Darwish', 'Noura Sami', 'Hana Youssef', 'Laila Mostafa', 'Salma Gaber', 'Amira Shafik', 'Khaled Nour'],
    replies: [],
  },
  {
    id: 'po-joiners-lunch',
    tribeId: 'tr-new-joiners',
    author: 'Dina Hafez',
    body: 'Welcome lunch is on Level 6 after the New Joiner Welcome. Nine of you started this quarter and I promise the building makes sense by about week three.',
    at: hoursAgo(13),
    kind: 'update',
    pinned: true,
    likes: ['Yara Sabry', 'Sami Kamal', 'Maya Fahmy', 'Waleed Tantawy', 'Lina Haddad'],
    replies: [{ author: 'Sami Kamal', body: 'Week three is generous. I still cannot find the Level 3 huddles.', at: hoursAgo(11) }],
  },
  {
    id: 'po-joiners-question',
    tribeId: 'tr-new-joiners',
    author: 'Waleed Tantawy',
    body: 'Silly question — can I book a focus pod for a whole afternoon, or is there an unwritten rule about hogging them?',
    at: hoursAgo(47),
    kind: 'question',
    pinned: false,
    likes: ['Yara Sabry'],
    replies: [
      { author: 'Maya Fahmy', body: 'Not silly. Two hours is polite, four gets you a look. Book it in SpaceOS and nobody minds.', at: hoursAgo(45) },
      { author: 'Waleed Tantawy', body: 'Two hours it is. Thank you.', at: hoursAgo(44) },
    ],
  },
];
